-- Nepali Recipes INSERT Statements
-- Converted from nepali_recipes_seed.json
-- Compatible with existing recipes table schema

USE `mood_food_recommender`;

-- Aloo Tama (Bamboo Shoot and Potato Curry)
INSERT INTO `recipes` (`title`, `slug`, `cuisine_id`, `description`, `image_url`, `is_veg`, `is_high_protein`, `calories`, `proteins_g`, `carbs_g`, `fats_g`, `prep_time`, `cook_time`, `servings`, `ingredients_json`, `steps_json`, `mood_tags_json`, `views_count`) VALUES
('Aloo Tama (Bamboo Shoot and Potato Curry)', 'aloo-tama-bamboo-shoot-and-potato-curry', 1, 'Traditional Nepali curry with bamboo shoots and potatoes - a comforting dish perfect for rainy days.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREC8kElU50EuHNl0mVayzKH7EyRBrUhZh_WA&s', 1, 0, 185, 4.5, 32.0, 5.2, 15, 30, 4,
'[{"qty": "2", "unit": "cups", "item": "bamboo shoots, sliced"}, {"qty": "3", "unit": "medium", "item": "potatoes, diced"}, {"qty": "1", "unit": "large", "item": "onion, finely chopped"}, {"qty": "3", "unit": "cloves", "item": "garlic, minced"}, {"qty": "1", "unit": "inch", "item": "ginger, grated"}, {"qty": "2", "unit": "tbsp", "item": "oil"}, {"qty": "1", "unit": "tsp", "item": "turmeric powder"}, {"qty": "1", "unit": "tsp", "item": "cumin seeds"}, {"qty": "1", "unit": "tsp", "item": "coriander powder"}, {"qty": "1/2", "unit": "tsp", "item": "red chili powder"}, {"qty": "1", "unit": "cup", "item": "water"}, {"qty": "2", "unit": "tbsp", "item": "fresh cilantro, chopped"}, {"qty": "1", "unit": "tsp", "item": "salt"}]',
'[{"step": 1, "instruction": "Heat oil in a large pan over medium heat. Add cumin seeds and let them splutter."}, {"step": 2, "instruction": "Add chopped onions and sauté until golden brown, about 5 minutes."}, {"step": 3, "instruction": "Add minced garlic and grated ginger, cook for 1 minute until fragrant."}, {"step": 4, "instruction": "Add turmeric, coriander powder, and red chili powder. Stir for 30 seconds."}, {"step": 5, "instruction": "Add diced potatoes and bamboo shoots. Mix well to coat with spices."}, {"step": 6, "instruction": "Add water and salt. Bring to a boil, then reduce heat and cover."}, {"step": 7, "instruction": "Simmer for 20-25 minutes until potatoes are tender and curry thickens."}, {"step": 8, "instruction": "Garnish with fresh cilantro and serve hot with rice or roti."}]',
'["stressed", "relaxed", "rainy"]', 0);

-- Kwati (Mixed Bean Soup)
INSERT INTO `recipes` (`title`, `slug`, `cuisine_id`, `description`, `image_url`, `is_veg`, `is_high_protein`, `calories`, `proteins_g`, `carbs_g`, `fats_g`, `prep_time`, `cook_time`, `servings`, `ingredients_json`, `steps_json`, `mood_tags_json`, `views_count`) VALUES
('Kwati (Mixed Bean Soup)', 'kwati-mixed-bean-soup', 1, 'Hearty Nepali soup made with nine different beans - a protein-rich traditional dish perfect for energy and comfort.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSy0mCsiu2uPqSSMnUPoGh6ZyRWGPEohCVVdw&s', 1, 1, 285, 22.5, 38.0, 6.8, 20, 90, 6,
'[{"qty": "1/2", "unit": "cup", "item": "black beans, soaked overnight"}, {"qty": "1/2", "unit": "cup", "item": "kidney beans, soaked overnight"}, {"qty": "1/2", "unit": "cup", "item": "chickpeas, soaked overnight"}, {"qty": "1/2", "unit": "cup", "item": "mung beans, soaked overnight"}, {"qty": "1/2", "unit": "cup", "item": "soybeans, soaked overnight"}, {"qty": "1", "unit": "large", "item": "onion, diced"}, {"qty": "4", "unit": "cloves", "item": "garlic, minced"}, {"qty": "2", "unit": "inch", "item": "ginger, grated"}, {"qty": "1", "unit": "tsp", "item": "turmeric powder"}, {"qty": "1", "unit": "tsp", "item": "cumin powder"}, {"qty": "1", "unit": "tsp", "item": "coriander powder"}, {"qty": "1/2", "unit": "tsp", "item": "asafoetida"}, {"qty": "2", "unit": "tbsp", "item": "ghee"}, {"qty": "6", "unit": "cups", "item": "water"}, {"qty": "2", "unit": "tbsp", "item": "fresh cilantro, chopped"}, {"qty": "1", "unit": "tsp", "item": "salt"}, {"qty": "1", "unit": "lemon", "item": "juiced"}]',
'[{"step": 1, "instruction": "Drain and rinse all soaked beans. Combine in a large pot."}, {"step": 2, "instruction": "Add 6 cups of water and bring to a boil. Skim off any foam."}, {"step": 3, "instruction": "Reduce heat, cover, and simmer for 60-75 minutes until beans are tender."}, {"step": 4, "instruction": "In a separate pan, heat ghee over medium heat. Add asafoetida and let it sizzle."}, {"step": 5, "instruction": "Add diced onion and sauté until translucent, about 5 minutes."}, {"step": 6, "instruction": "Add garlic and ginger, cook for 2 minutes until fragrant."}, {"step": 7, "instruction": "Add turmeric, cumin, and coriander powder. Stir for 30 seconds."}, {"step": 8, "instruction": "Add this spice mixture to the cooked beans. Season with salt."}, {"step": 9, "instruction": "Simmer for another 10-15 minutes until flavors meld together."}, {"step": 10, "instruction": "Stir in lemon juice, garnish with cilantro, and serve hot."}]',
'["tired", "relaxed", "rainy"]', 0);

-- Chicken Sekuwa (Grilled Spiced Chicken)
INSERT INTO `recipes` (`title`, `slug`, `cuisine_id`, `description`, `image_url`, `is_veg`, `is_high_protein`, `calories`, `proteins_g`, `carbs_g`, `fats_g`, `prep_time`, `cook_time`, `servings`, `ingredients_json`, `steps_json`, `mood_tags_json`, `views_count`) VALUES
('Chicken Sekuwa (Grilled Spiced Chicken)', 'chicken-sekuwa-grilled-spiced-chicken', 1, 'Tender, marinated chicken grilled to perfection with aromatic Nepali spices - a flavorful dish that brings joy and energy.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYgxDJYGEQZN53Zpi1aqfox1muLe8FSP0Yqw&s', 0, 0, 320, 28.0, 8.0, 18.0, 30, 20, 4,
'[{"qty": "1.5", "unit": "lbs", "item": "chicken thighs, cut into bite-sized pieces"}, {"qty": "1", "unit": "cup", "item": "plain yogurt"}, {"qty": "2", "unit": "tbsp", "item": "mustard oil"}, {"qty": "1", "unit": "tbsp", "item": "ginger-garlic paste"}, {"qty": "1", "unit": "tsp", "item": "turmeric powder"}, {"qty": "1", "unit": "tsp", "item": "cumin powder"}, {"qty": "1", "unit": "tsp", "item": "coriander powder"}, {"qty": "1", "unit": "tsp", "item": "red chili powder"}, {"qty": "1/2", "unit": "tsp", "item": "garam masala"}, {"qty": "1", "unit": "tsp", "item": "salt"}, {"qty": "2", "unit": "tbsp", "item": "lemon juice"}, {"qty": "1", "unit": "onion", "item": "sliced for garnish"}, {"qty": "2", "unit": "tbsp", "item": "fresh cilantro, chopped"}]',
'[{"step": 1, "instruction": "In a large bowl, mix yogurt, mustard oil, and all spice powders."}, {"step": 2, "instruction": "Add ginger-garlic paste, salt, and lemon juice. Mix well to form a marinade."}, {"step": 3, "instruction": "Add chicken pieces to the marinade, ensuring all pieces are well coated."}, {"step": 4, "instruction": "Cover and marinate in refrigerator for at least 2 hours (overnight preferred)."}, {"step": 5, "instruction": "Preheat grill or grill pan to medium-high heat."}, {"step": 6, "instruction": "Thread marinated chicken onto skewers or place directly on grill."}, {"step": 7, "instruction": "Grill for 8-10 minutes per side, turning occasionally, until chicken is cooked through and charred."}, {"step": 8, "instruction": "Garnish with sliced onions and fresh cilantro. Serve hot with rice or naan."}]',
'["happy", "angry", "sunny"]', 0);

-- Mutton Khasi Ko Masu (Spiced Mutton Curry)
INSERT INTO `recipes` (`title`, `slug`, `cuisine_id`, `description`, `image_url`, `is_veg`, `is_high_protein`, `calories`, `proteins_g`, `carbs_g`, `fats_g`, `prep_time`, `cook_time`, `servings`, `ingredients_json`, `steps_json`, `mood_tags_json`, `views_count`) VALUES
('Mutton Khasi Ko Masu (Spiced Mutton Curry)', 'mutton-khasi-ko-masu-spiced-mutton-curry', 1, 'Rich, aromatic mutton curry slow-cooked with traditional Nepali spices - a hearty, protein-packed comfort dish.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-1jvsYyZ9Qo0Snmuf-4UK6dJDeR2fVGEbpQ&s', 0, 1, 385, 35.0, 12.0, 22.0, 25, 75, 5,
'[{"qty": "2", "unit": "lbs", "item": "mutton (goat meat), cut into pieces"}, {"qty": "2", "unit": "large", "item": "onions, finely chopped"}, {"qty": "6", "unit": "cloves", "item": "garlic, minced"}, {"qty": "2", "unit": "inch", "item": "ginger, grated"}, {"qty": "2", "unit": "large", "item": "tomatoes, pureed"}, {"qty": "1/4", "unit": "cup", "item": "mustard oil"}, {"qty": "1", "unit": "tsp", "item": "turmeric powder"}, {"qty": "2", "unit": "tsp", "item": "cumin powder"}, {"qty": "2", "unit": "tsp", "item": "coriander powder"}, {"qty": "1", "unit": "tsp", "item": "red chili powder"}, {"qty": "1", "unit": "tsp", "item": "garam masala"}, {"qty": "2", "unit": "bay leaves"}, {"qty": "4", "unit": "cloves", "item": "whole cloves"}, {"qty": "2", "unit": "inch", "item": "cinnamon stick"}, {"qty": "1", "unit": "cup", "item": "water"}, {"qty": "2", "unit": "tbsp", "item": "fresh cilantro, chopped"}, {"qty": "1.5", "unit": "tsp", "item": "salt"}]',
'[{"step": 1, "instruction": "Heat mustard oil in a large heavy-bottomed pot over medium-high heat."}, {"step": 2, "instruction": "Add bay leaves, cloves, and cinnamon stick. Sauté for 30 seconds until fragrant."}, {"step": 3, "instruction": "Add chopped onions and cook until golden brown, about 8-10 minutes."}, {"step": 4, "instruction": "Add minced garlic and grated ginger. Cook for 2 minutes until fragrant."}, {"step": 5, "instruction": "Add all spice powders (turmeric, cumin, coriander, red chili) and stir for 1 minute."}, {"step": 6, "instruction": "Add mutton pieces and cook on high heat for 5 minutes, stirring to seal the meat."}, {"step": 7, "instruction": "Add tomato puree and salt. Mix well and cook for 5 minutes."}, {"step": 8, "instruction": "Add water, bring to a boil, then reduce heat to low. Cover and simmer for 60 minutes."}, {"step": 9, "instruction": "Stir occasionally and add more water if needed. Cook until mutton is tender."}, {"step": 10, "instruction": "Sprinkle garam masala, garnish with cilantro, and serve hot with rice or roti."}]',
'["stressed", "tired", "rainy"]', 0);

