-- Sample Data for Mood-Based Recipe Recommender
-- Insert after running schema.sql

USE `mood_food_recommender`;

-- Insert Moods
INSERT INTO `moods` (`name`, `slug`, `description`, `icon`, `color`, `food_intent`) VALUES
('Happy', 'happy', 'Celebrate with bright, colorful, and uplifting foods!', '😊', '#FFB6C1', 'Celebratory, light, bright, colorful, sweet treats, fresh ingredients'),
('Stressed', 'stressed', 'Comfort foods to soothe and relax your mind.', '😰', '#FFA0B4', 'Comforting, warm, soothing, hearty, familiar flavors, stress-relieving ingredients'),
('Tired', 'tired', 'Energy-boosting meals to recharge and revitalize.', '😴', '#FF8FA3', 'High protein, energizing, nutrient-dense, quick to prepare, caffeine-rich options'),
('Bored', 'bored', 'Fun, creative dishes to spark curiosity and joy.', '🤔', '#FF92B6', 'Fusion meals, playful plating, unexpected textures and toppings'),
('Romantic', 'romantic', 'Cozy, aesthetic meals perfect for special moments.', '❤️', '#FF6D8C', 'Pastas, chocolate desserts, candlelight-ready comfort dishes'),
('Angry', 'angry', 'Crunchy, spicy dishes to release tension and fire up tastebuds.', '😡', '#FF4F6E', 'Chili noodles, crispy snacks, bold heat-forward flavors'),
('Relaxed', 'relaxed', 'Mild, warm, slow-food plates to keep you grounded.', '😌', '#FDB7D0', 'Tea blends, stews, slow-simmered soups and congee'),
('Rainy', 'rainy', 'Cozy, warm comfort bowls for grey-day cuddles.', '🌧️', '#B0E0E6', 'Pakoras, spiced teas, steamed buns, brothy noodles'),
('Sunny', 'sunny', 'Fresh, cool bites that feel like sunshine.', '☀️', '#FFD27F', 'Citrus salads, iced drinks, chilled noodles, seasonal fruits');

-- Insert Cuisines
INSERT INTO `cuisines` (`name`, `slug`, `flag_emoji`) VALUES
('Nepali', 'nepali', '🇳🇵'),
('Indian', 'indian', '🇮🇳'),
('American', 'american', '🇺🇸'),
('Chinese', 'chinese', '🇨🇳'),
('Japanese', 'japanese', '🇯🇵'),
('Italian', 'italian', '🇮🇹'),
('Coffee Shop', 'coffee-shop', '☕');

-- Insert Sample Recipes (15 recipes across moods and cuisines)

-- Happy Mood Recipes
INSERT INTO `recipes` (`title`, `slug`, `cuisine_id`, `description`, `image_url`, `is_veg`, `is_high_protein`, `calories`, `proteins_g`, `carbs_g`, `fats_g`, `prep_time`, `cook_time`, `servings`, `ingredients_json`, `steps_json`, `mood_tags_json`, `views_count`) VALUES
('Vibrant Rainbow Fruit Salad', 'vibrant-rainbow-fruit-salad', 3, 'A colorful explosion of fresh fruits that brings instant joy and brightens any day!', 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800', 1, 0, 180, 2.5, 42.0, 0.8, 15, 0, 4,
'[{"qty": "2", "unit": "cups", "item": "strawberries, sliced"}, {"qty": "1", "unit": "cup", "item": "blueberries"}, {"qty": "1", "unit": "cup", "item": "mango, diced"}, {"qty": "1", "unit": "cup", "item": "pineapple chunks"}, {"qty": "1", "unit": "cup", "item": "kiwi, sliced"}, {"qty": "1", "unit": "cup", "item": "grapes, halved"}, {"qty": "1/4", "unit": "cup", "item": "honey"}, {"qty": "2", "unit": "tbsp", "item": "lime juice"}, {"qty": "1", "unit": "tbsp", "item": "fresh mint leaves"}, {"qty": "1/4", "unit": "cup", "item": "pomegranate seeds"}]',
'[{"step": 1, "instruction": "Wash and prepare all fruits, cutting them into bite-sized pieces."}, {"step": 2, "instruction": "In a large bowl, gently combine all the fruits together."}, {"step": 3, "instruction": "In a small bowl, whisk together honey and lime juice to create a dressing."}, {"step": 4, "instruction": "Drizzle the dressing over the fruit salad and toss gently."}, {"step": 5, "instruction": "Garnish with fresh mint leaves and pomegranate seeds. Serve chilled and enjoy!"}]',
'["happy"]', 234),

('Cheerful Lemon Blueberry Muffins', 'cheerful-lemon-blueberry-muffins', 3, 'Bright, fluffy muffins bursting with sweet blueberries and zesty lemon - pure happiness in every bite!', 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=800', 1, 0, 285, 5.0, 48.0, 9.5, 15, 20, 12,
'[{"qty": "2", "unit": "cups", "item": "all-purpose flour"}, {"qty": "1/2", "unit": "cup", "item": "granulated sugar"}, {"qty": "2", "unit": "tsp", "item": "baking powder"}, {"qty": "1/2", "unit": "tsp", "item": "baking soda"}, {"qty": "1/2", "unit": "tsp", "item": "salt"}, {"qty": "1", "unit": "cup", "item": "buttermilk"}, {"qty": "1/3", "unit": "cup", "item": "vegetable oil"}, {"qty": "1", "unit": "large", "item": "egg"}, {"qty": "1", "unit": "tbsp", "item": "lemon zest"}, {"qty": "2", "unit": "tbsp", "item": "lemon juice"}, {"qty": "1.5", "unit": "cups", "item": "fresh blueberries"}, {"qty": "2", "unit": "tbsp", "item": "turbinado sugar for topping"}]',
'[{"step": 1, "instruction": "Preheat oven to 400°F. Line a 12-cup muffin tin with paper liners."}, {"step": 2, "instruction": "In a large bowl, whisk together flour, sugar, baking powder, baking soda, and salt."}, {"step": 3, "instruction": "In another bowl, mix buttermilk, oil, egg, lemon zest, and lemon juice."}, {"step": 4, "instruction": "Pour wet ingredients into dry ingredients and stir until just combined. Gently fold in blueberries."}, {"step": 5, "instruction": "Divide batter evenly among muffin cups. Sprinkle with turbinado sugar. Bake 18-20 minutes until golden. Cool before serving."}]',
'["happy"]', 189),

('Sunshine Yellow Curry with Vegetables', 'sunshine-yellow-curry-vegetables', 2, 'A bright, cheerful yellow curry loaded with colorful vegetables that brings warmth and happiness!', 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800', 1, 0, 320, 8.5, 52.0, 10.5, 20, 25, 4,
'[{"qty": "2", "unit": "tbsp", "item": "coconut oil"}, {"qty": "1", "unit": "large", "item": "onion, diced"}, {"qty": "3", "unit": "cloves", "item": "garlic, minced"}, {"qty": "1", "unit": "tbsp", "item": "fresh ginger, grated"}, {"qty": "2", "unit": "tbsp", "item": "yellow curry paste"}, {"qty": "1", "unit": "can (14oz)", "item": "coconut milk"}, {"qty": "1", "unit": "cup", "item": "sweet potato, cubed"}, {"qty": "1", "unit": "cup", "item": "carrots, sliced"}, {"qty": "1", "unit": "cup", "item": "red bell pepper, sliced"}, {"qty": "1", "unit": "cup", "item": "cauliflower florets"}, {"qty": "1", "unit": "cup", "item": "broccoli florets"}, {"qty": "2", "unit": "tbsp", "item": "soy sauce"}, {"qty": "1", "unit": "tbsp", "item": "brown sugar"}, {"qty": "1/4", "unit": "cup", "item": "fresh basil leaves"}, {"qty": "2", "unit": "cups", "item": "cooked jasmine rice"}]',
'[{"step": 1, "instruction": "Heat coconut oil in a large pot over medium heat. Add onion and sauté until translucent, about 5 minutes."}, {"step": 2, "instruction": "Add garlic, ginger, and yellow curry paste. Cook for 2 minutes until fragrant."}, {"step": 3, "instruction": "Pour in coconut milk and bring to a gentle simmer. Add sweet potato and carrots, cook for 10 minutes."}, {"step": 4, "instruction": "Add bell pepper, cauliflower, and broccoli. Cook for another 8-10 minutes until vegetables are tender."}, {"step": 5, "instruction": "Stir in soy sauce and brown sugar. Garnish with fresh basil. Serve over jasmine rice."}]',
'["happy"]', 156),

('Joyful Chocolate Chip Cookies', 'joyful-chocolate-chip-cookies', 3, 'Classic, chewy chocolate chip cookies that spread happiness and bring smiles to everyone!', 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800', 1, 0, 145, 2.0, 18.0, 7.5, 15, 12, 24,
'[{"qty": "2.25", "unit": "cups", "item": "all-purpose flour"}, {"qty": "1", "unit": "tsp", "item": "baking soda"}, {"qty": "1", "unit": "tsp", "item": "salt"}, {"qty": "1", "unit": "cup", "item": "butter, softened"}, {"qty": "3/4", "unit": "cup", "item": "granulated sugar"}, {"qty": "3/4", "unit": "cup", "item": "brown sugar"}, {"qty": "2", "unit": "large", "item": "eggs"}, {"qty": "2", "unit": "tsp", "item": "vanilla extract"}, {"qty": "2", "unit": "cups", "item": "chocolate chips"}, {"qty": "1", "unit": "cup", "item": "walnuts, chopped (optional)"}]',
'[{"step": 1, "instruction": "Preheat oven to 375°F. Line baking sheets with parchment paper."}, {"step": 2, "instruction": "In a medium bowl, whisk together flour, baking soda, and salt. Set aside."}, {"step": 3, "instruction": "In a large bowl, cream butter and both sugars until light and fluffy, about 3 minutes."}, {"step": 4, "instruction": "Beat in eggs one at a time, then add vanilla extract. Gradually mix in flour mixture."}, {"step": 5, "instruction": "Stir in chocolate chips and walnuts. Drop rounded tablespoons onto baking sheets. Bake 9-11 minutes until golden. Cool on wire rack."}]',
'["happy"]', 312),

('Bright Caprese Salad', 'bright-caprese-salad', 6, 'A vibrant, fresh Italian salad with colorful tomatoes, creamy mozzarella, and aromatic basil - pure joy on a plate!', 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800', 1, 0, 220, 12.0, 8.0, 16.0, 10, 0, 4,
'[{"qty": "4", "unit": "large", "item": "ripe tomatoes, sliced"}, {"qty": "8", "unit": "oz", "item": "fresh mozzarella, sliced"}, {"qty": "1/4", "unit": "cup", "item": "fresh basil leaves"}, {"qty": "3", "unit": "tbsp", "item": "extra virgin olive oil"}, {"qty": "1", "unit": "tbsp", "item": "balsamic vinegar"}, {"qty": "1/2", "unit": "tsp", "item": "salt"}, {"qty": "1/4", "unit": "tsp", "item": "black pepper"}, {"qty": "1", "unit": "tsp", "item": "balsamic glaze"}]',
'[{"step": 1, "instruction": "Arrange tomato and mozzarella slices alternately on a serving platter in a circular pattern."}, {"step": 2, "instruction": "Tuck fresh basil leaves between the slices throughout the arrangement."}, {"step": 3, "instruction": "Drizzle with extra virgin olive oil and balsamic vinegar."}, {"step": 4, "instruction": "Season with salt and black pepper to taste."}, {"step": 5, "instruction": "Finish with a drizzle of balsamic glaze. Serve immediately and enjoy the fresh flavors!"}]',
'["happy"]', 178),

('Happy Berry Smoothie Bowl', 'happy-berry-smoothie-bowl', 3, 'A colorful, Instagram-worthy smoothie bowl topped with fresh berries and granola - breakfast that makes you smile!', 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800', 1, 1, 320, 15.0, 52.0, 8.0, 10, 0, 1,
'[{"qty": "1", "unit": "cup", "item": "frozen mixed berries"}, {"qty": "1", "unit": "banana", "item": "frozen"}, {"qty": "1/2", "unit": "cup", "item": "Greek yogurt"}, {"qty": "1/4", "unit": "cup", "item": "almond milk"}, {"qty": "1", "unit": "tbsp", "item": "honey"}, {"qty": "1/4", "unit": "cup", "item": "fresh strawberries, sliced"}, {"qty": "1/4", "unit": "cup", "item": "fresh blueberries"}, {"qty": "2", "unit": "tbsp", "item": "granola"}, {"qty": "1", "unit": "tbsp", "item": "chia seeds"}, {"qty": "1", "unit": "tbsp", "item": "coconut flakes"}]',
'[{"step": 1, "instruction": "Blend frozen berries, banana, Greek yogurt, almond milk, and honey until smooth and thick."}, {"step": 2, "instruction": "Pour the smoothie into a bowl, creating a smooth surface on top."}, {"step": 3, "instruction": "Artistically arrange fresh strawberries and blueberries on one side of the bowl."}, {"step": 4, "instruction": "Sprinkle granola, chia seeds, and coconut flakes in decorative patterns."}, {"step": 5, "instruction": "Serve immediately with a spoon and enjoy your beautiful, nutritious breakfast!"}]',
'["happy"]', 267),

('Colorful Veggie Spring Rolls', 'colorful-veggie-spring-rolls', 4, 'Fresh, vibrant spring rolls filled with colorful vegetables - a fun and healthy treat that brings joy!', 'https://images.unsplash.com/photo-1615367423057-4b9b09b7488a?w=800', 1, 0, 95, 2.5, 20.0, 0.5, 25, 0, 8,
'[{"qty": "8", "unit": "sheets", "item": "rice paper wrappers"}, {"qty": "1", "unit": "cup", "item": "carrots, julienned"}, {"qty": "1", "unit": "cup", "item": "red cabbage, thinly sliced"}, {"qty": "1", "unit": "cup", "item": "bell peppers, julienned"}, {"qty": "1/2", "unit": "cup", "item": "cucumber, julienned"}, {"qty": "1/2", "unit": "cup", "item": "fresh mint leaves"}, {"qty": "1/2", "unit": "cup", "item": "fresh cilantro"}, {"qty": "1/4", "unit": "cup", "item": "peanut sauce"}, {"qty": "2", "unit": "tbsp", "item": "lime juice"}]',
'[{"step": 1, "instruction": "Prepare all vegetables by cutting them into thin, uniform strips."}, {"step": 2, "instruction": "Fill a large shallow dish with warm water. Dip one rice paper wrapper for 10-15 seconds until pliable."}, {"step": 3, "instruction": "Place wrapper on a clean surface. Arrange a small amount of each vegetable in the center, leaving space on edges."}, {"step": 4, "instruction": "Add a few mint and cilantro leaves. Fold the bottom edge over filling, then fold in sides, and roll tightly."}, {"step": 5, "instruction": "Repeat with remaining wrappers. Serve with peanut sauce and a squeeze of lime juice."}]',
'["happy"]', 145),

('Cheerful Pancake Stack with Berries', 'cheerful-pancake-stack-berries', 3, 'Fluffy golden pancakes stacked high and topped with fresh berries - a breakfast that starts your day with a big smile!', 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800', 1, 0, 380, 10.0, 58.0, 12.0, 10, 15, 3,
'[{"qty": "1.5", "unit": "cups", "item": "all-purpose flour"}, {"qty": "3.5", "unit": "tsp", "item": "baking powder"}, {"qty": "1", "unit": "tsp", "item": "salt"}, {"qty": "1", "unit": "tbsp", "item": "white sugar"}, {"qty": "1.25", "unit": "cups", "item": "milk"}, {"qty": "1", "unit": "large", "item": "egg"}, {"qty": "3", "unit": "tbsp", "item": "butter, melted"}, {"qty": "1", "unit": "cup", "item": "mixed fresh berries"}, {"qty": "2", "unit": "tbsp", "item": "maple syrup"}, {"qty": "1", "unit": "tbsp", "item": "powdered sugar"}]',
'[{"step": 1, "instruction": "In a large bowl, sift together flour, baking powder, salt, and sugar."}, {"step": 2, "instruction": "Make a well in the center and pour in milk, egg, and melted butter. Mix until smooth."}, {"step": 3, "instruction": "Heat a lightly oiled griddle or frying pan over medium-high heat. Pour batter onto griddle, using approximately 1/4 cup for each pancake."}, {"step": 4, "instruction": "Cook until bubbles form and edges are dry. Flip and cook until browned on the other side."}, {"step": 5, "instruction": "Stack pancakes on a plate, top with fresh berries, drizzle with maple syrup, and dust with powdered sugar. Serve warm!"}]',
'["happy"]', 298),

('Sunny Mango Sticky Rice', 'sunny-mango-sticky-rice', 4, 'Sweet, tropical sticky rice with fresh mango - a bright and cheerful Thai dessert that brings pure joy!', 'https://assets.epicurious.com/photos/6070a9f1d3a2a6911a3f52f0/1:1/w_2560%2Cc_limit/CoconutStickyRiceWithMango_RECIPE_040821_12932.jpg', 1, 0, 420, 5.5, 88.0, 8.0, 10, 30, 4,
'[{"qty": "1", "unit": "cup", "item": "glutinous rice (sticky rice)"}, {"qty": "1", "unit": "can (13.5oz)", "item": "coconut milk"}, {"qty": "1/3", "unit": "cup", "item": "white sugar"}, {"qty": "1/2", "unit": "tsp", "item": "salt"}, {"qty": "2", "unit": "large", "item": "ripe mangoes, sliced"}, {"qty": "1", "unit": "tbsp", "item": "toasted sesame seeds"}, {"qty": "1", "unit": "tbsp", "item": "coconut cream for drizzling"}]',
'[{"step": 1, "instruction": "Soak glutinous rice in water for at least 4 hours or overnight. Drain well."}, {"step": 2, "instruction": "Steam the rice for 20-25 minutes until tender and translucent."}, {"step": 3, "instruction": "While rice is steaming, heat coconut milk, sugar, and salt in a saucepan until sugar dissolves. Do not boil."}, {"step": 4, "instruction": "Transfer hot steamed rice to a bowl. Pour coconut milk mixture over rice and let it absorb for 20 minutes."}, {"step": 5, "instruction": "Serve sticky rice with fresh mango slices, drizzle with coconut cream, and sprinkle with sesame seeds."}]',
'["happy"]', 201),

('Joyful Fruit Tart', 'joyful-fruit-tart', 6, 'A beautiful, colorful fruit tart with a buttery crust and fresh seasonal fruits - a delightful dessert that spreads happiness!', 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800', 1, 0, 265, 4.0, 38.0, 12.0, 30, 25, 8,
'[{"qty": "1.5", "unit": "cups", "item": "all-purpose flour"}, {"qty": "1/2", "unit": "cup", "item": "butter, cold and cubed"}, {"qty": "1/4", "unit": "cup", "item": "granulated sugar"}, {"qty": "1", "unit": "large", "item": "egg yolk"}, {"qty": "2", "unit": "tbsp", "item": "ice water"}, {"qty": "1", "unit": "cup", "item": "pastry cream"}, {"qty": "2", "unit": "cups", "item": "mixed fresh fruits (berries, kiwi, mango)"}, {"qty": "1/4", "unit": "cup", "item": "apricot jam, warmed"}, {"qty": "1", "unit": "tbsp", "item": "lemon juice"}]',
'[{"step": 1, "instruction": "Make pastry: Mix flour and sugar. Cut in cold butter until mixture resembles coarse crumbs."}, {"step": 2, "instruction": "Add egg yolk and ice water. Mix until dough forms. Chill for 30 minutes."}, {"step": 3, "instruction": "Roll out dough and press into tart pan. Prick bottom with fork. Bake at 375°F for 15-20 minutes until golden. Cool completely."}, {"step": 4, "instruction": "Spread pastry cream evenly in cooled tart shell."}, {"step": 5, "instruction": "Arrange fresh fruits artistically on top. Brush with warmed apricot jam mixed with lemon juice for a glossy finish. Chill before serving."}]',
'["happy"]', 223),

('Bright Tropical Poke Bowl', 'bright-tropical-poke-bowl', 5, 'A vibrant Hawaiian-inspired bowl with colorful fresh fish, tropical fruits, and bright vegetables - pure island joy!', 'https://www.giallozafferano.com/images/338-33898/salmon-and-fruit-poke-bowl_1200x800.jpg', 0, 1, 485, 32.0, 55.0, 12.0, 20, 0, 2,
'[{"qty": "8", "unit": "oz", "item": "fresh ahi tuna, cubed"}, {"qty": "2", "unit": "cups", "item": "sushi rice, cooked"}, {"qty": "1/4", "unit": "cup", "item": "soy sauce"}, {"qty": "1", "unit": "tbsp", "item": "sesame oil"}, {"qty": "1", "unit": "tbsp", "item": "rice vinegar"}, {"qty": "1/2", "unit": "cup", "item": "mango, diced"}, {"qty": "1/2", "unit": "cup", "item": "avocado, sliced"}, {"qty": "1/4", "unit": "cup", "item": "edamame"}, {"qty": "1/4", "unit": "cup", "item": "cucumber, diced"}, {"qty": "1", "unit": "tbsp", "item": "scallions, chopped"}, {"qty": "1", "unit": "tbsp", "item": "sesame seeds"}, {"qty": "1", "unit": "tsp", "item": "wasabi"}]',
'[{"step": 1, "instruction": "Marinate cubed tuna in soy sauce, sesame oil, and rice vinegar for 10 minutes."}, {"step": 2, "instruction": "Divide cooked sushi rice between two bowls, creating a base layer."}, {"step": 3, "instruction": "Arrange marinated tuna, mango, avocado, edamame, and cucumber in colorful sections on top of rice."}, {"step": 4, "instruction": "Garnish with chopped scallions and sesame seeds."}, {"step": 5, "instruction": "Serve with wasabi on the side. Mix everything together before eating for the best flavor!"}]',
'["happy"]', 189),

('Cheerful Rainbow Quinoa Salad', 'cheerful-rainbow-quinoa-salad', 3, 'A stunning rainbow-colored quinoa salad packed with colorful vegetables - healthy, beautiful, and full of joy!', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800', 1, 1, 285, 12.0, 42.0, 8.5, 20, 15, 4,
'[{"qty": "1", "unit": "cup", "item": "quinoa, cooked and cooled"}, {"qty": "1/2", "unit": "cup", "item": "cherry tomatoes, halved"}, {"qty": "1/2", "unit": "cup", "item": "yellow bell pepper, diced"}, {"qty": "1/2", "unit": "cup", "item": "red bell pepper, diced"}, {"qty": "1/2", "unit": "cup", "item": "carrots, shredded"}, {"qty": "1/2", "unit": "cup", "item": "purple cabbage, shredded"}, {"qty": "1/4", "unit": "cup", "item": "red onion, diced"}, {"qty": "1/4", "unit": "cup", "item": "fresh parsley, chopped"}, {"qty": "3", "unit": "tbsp", "item": "olive oil"}, {"qty": "2", "unit": "tbsp", "item": "lemon juice"}, {"qty": "1", "unit": "tsp", "item": "honey"}, {"qty": "1/2", "unit": "tsp", "item": "salt"}]',
'[{"step": 1, "instruction": "Cook quinoa according to package directions and let cool completely."}, {"step": 2, "instruction": "In a large bowl, combine cooked quinoa with all the colorful vegetables."}, {"step": 3, "instruction": "In a small bowl, whisk together olive oil, lemon juice, honey, and salt to make the dressing."}, {"step": 4, "instruction": "Pour dressing over the quinoa salad and toss gently to combine."}, {"step": 5, "instruction": "Garnish with fresh parsley. Serve chilled or at room temperature. Enjoy the beautiful colors!"}]',
'["happy"]', 167),

('Sunny Citrus Cheesecake', 'sunny-citrus-cheesecake', 3, 'A bright, zesty cheesecake with a citrus twist - creamy, refreshing, and guaranteed to bring smiles!', 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800', 1, 0, 385, 7.0, 32.0, 26.0, 25, 60, 10,
'[{"qty": "1.5", "unit": "cups", "item": "graham cracker crumbs"}, {"qty": "6", "unit": "tbsp", "item": "butter, melted"}, {"qty": "2", "unit": "lbs", "item": "cream cheese, softened"}, {"qty": "1", "unit": "cup", "item": "granulated sugar"}, {"qty": "4", "unit": "large", "item": "eggs"}, {"qty": "1", "unit": "tbsp", "item": "lemon zest"}, {"qty": "2", "unit": "tbsp", "item": "lemon juice"}, {"qty": "1", "unit": "tbsp", "item": "orange zest"}, {"qty": "1", "unit": "tbsp", "item": "orange juice"}, {"qty": "1", "unit": "tsp", "item": "vanilla extract"}, {"qty": "1", "unit": "cup", "item": "sour cream"}, {"qty": "1/4", "unit": "cup", "item": "fresh berries for garnish"}]',
'[{"step": 1, "instruction": "Preheat oven to 325°F. Mix graham cracker crumbs with melted butter. Press into bottom of 9-inch springform pan."}, {"step": 2, "instruction": "Bake crust for 10 minutes. Let cool. Wrap pan bottom with foil for water bath."}, {"step": 3, "instruction": "Beat cream cheese and sugar until smooth. Add eggs one at a time, then lemon and orange zest and juices, vanilla, and sour cream."}, {"step": 4, "instruction": "Pour filling over crust. Place pan in larger pan filled with hot water. Bake 60 minutes until set but center jiggles slightly."}, {"step": 5, "instruction": "Turn off oven, crack door, let cool 1 hour. Chill 4 hours. Garnish with fresh berries before serving."}]',
'["happy"]', 245),

('Joyful Veggie Pizza', 'joyful-veggie-pizza', 6, 'A colorful, cheerful pizza loaded with bright vegetables and fresh herbs - happiness shared on a pizza!', 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800', 1, 0, 295, 12.0, 38.0, 11.0, 20, 15, 4,
'[{"qty": "1", "unit": "lb", "item": "pizza dough"}, {"qty": "1/2", "unit": "cup", "item": "tomato sauce"}, {"qty": "1", "unit": "cup", "item": "mozzarella cheese, shredded"}, {"qty": "1/2", "unit": "cup", "item": "red bell pepper, sliced"}, {"qty": "1/2", "unit": "cup", "item": "yellow bell pepper, sliced"}, {"qty": "1/2", "unit": "cup", "item": "broccoli florets"}, {"qty": "1/4", "unit": "cup", "item": "red onion, sliced"}, {"qty": "1/4", "unit": "cup", "item": "black olives, sliced"}, {"qty": "1/4", "unit": "cup", "item": "fresh basil leaves"}, {"qty": "2", "unit": "tbsp", "item": "olive oil"}]',
'[{"step": 1, "instruction": "Preheat oven to 475°F. Roll out pizza dough on a floured surface to desired thickness."}, {"step": 2, "instruction": "Transfer dough to pizza pan or baking sheet. Spread tomato sauce evenly over dough."}, {"step": 3, "instruction": "Sprinkle mozzarella cheese over sauce. Arrange colorful vegetables in an attractive pattern."}, {"step": 4, "instruction": "Drizzle with olive oil. Bake for 12-15 minutes until crust is golden and cheese is bubbly."}, {"step": 5, "instruction": "Remove from oven, top with fresh basil leaves, slice, and serve hot. Enjoy the colorful feast!"}]',
'["happy"]', 278),


('Colorful Mango Lassi', 'colorful-mango-lassi', 2, 'A vibrant, sweet Nepali-inspired drink that brings joy with every sip!', 'https://assets.epicurious.com/photos/6070a9f1d3a2a6911a3f52f0/1:1/w_2560%2Cc_limit/CoconutStickyRiceWithMango_RECIPE_040821_12932.jpg', 1, 0, 180, 8.5, 35.0, 2.5, 5, 0, 2, 
'[{"qty": "2", "unit": "cups", "item": "ripe mango, diced"}, {"qty": "1", "unit": "cup", "item": "plain yogurt"}, {"qty": "2", "unit": "tbsp", "item": "honey"}, {"qty": "1/2", "unit": "cup", "item": "ice cubes"}, {"qty": "1", "unit": "pinch", "item": "cardamom powder"}]',
'[{"step": 1, "instruction": "Blend mango, yogurt, and honey until smooth."}, {"step": 2, "instruction": "Add ice cubes and cardamom, blend again."}, {"step": 3, "instruction": "Pour into glasses and garnish with mango slices."}]',
'["happy"]', 45),

('Rainbow Veggie Spring Rolls', 'rainbow-veggie-spring-rolls', 4, 'Bright, fresh, and fun spring rolls that make any meal a celebration!', 'https://images.unsplash.com/photo-1615367423057-4b9b09b7488a?w=800', 1, 0, 120, 3.0, 25.0, 1.0, 20, 5, 4,
'[{"qty": "8", "unit": "sheets", "item": "rice paper wrappers"}, {"qty": "1", "unit": "cup", "item": "shredded carrots"}, {"qty": "1", "unit": "cup", "item": "red cabbage, sliced"}, {"qty": "1", "unit": "cup", "item": "bell peppers, julienned"}, {"qty": "1/2", "unit": "cup", "item": "fresh mint leaves"}, {"qty": "1/4", "unit": "cup", "item": "peanut sauce"}]',
'[{"step": 1, "instruction": "Soak rice paper in warm water for 10 seconds."}, {"step": 2, "instruction": "Place vegetables in center, fold sides, and roll tightly."}, {"step": 3, "instruction": "Serve with peanut sauce for dipping."}]',
'["happy"]', 38),

('Cheerful Margherita Pizza', 'cheerful-margherita-pizza', 6, 'Classic Italian pizza with fresh basil and vibrant tomatoes - pure happiness on a plate!', 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800', 1, 0, 285, 12.0, 36.0, 10.0, 15, 12, 2,
'[{"qty": "1", "unit": "lb", "item": "pizza dough"}, {"qty": "1/2", "unit": "cup", "item": "tomato sauce"}, {"qty": "8", "unit": "oz", "item": "fresh mozzarella"}, {"qty": "10", "unit": "leaves", "item": "fresh basil"}, {"qty": "2", "unit": "tbsp", "item": "olive oil"}]',
'[{"step": 1, "instruction": "Preheat oven to 475°F. Roll out dough."}, {"step": 2, "instruction": "Spread sauce, add cheese, and bake for 10-12 minutes."}, {"step": 3, "instruction": "Top with fresh basil and drizzle olive oil."}]',
'["happy"]', 52),

('Sunshine Pancake Stack', 'sunshine-pancake-stack', 3, 'Fluffy, golden pancakes topped with fresh berries - a breakfast that starts your day with a smile!', 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800', 1, 0, 320, 8.0, 45.0, 12.0, 10, 15, 3,
'[{"qty": "1", "unit": "cup", "item": "all-purpose flour"}, {"qty": "2", "unit": "tbsp", "item": "sugar"}, {"qty": "1", "unit": "tsp", "item": "baking powder"}, {"qty": "1", "unit": "cup", "item": "milk"}, {"qty": "1", "unit": "large", "item": "egg"}, {"qty": "1", "unit": "cup", "item": "mixed berries"}]',
'[{"step": 1, "instruction": "Mix dry ingredients in a bowl."}, {"step": 2, "instruction": "Whisk in wet ingredients until smooth."}, {"step": 3, "instruction": "Cook pancakes on griddle until golden. Top with berries."}]',
'["happy"]', 67);

-- Stressed Mood Recipes
INSERT INTO `recipes` (`title`, `slug`, `cuisine_id`, `description`, `image_url`, `is_veg`, `is_high_protein`, `calories`, `proteins_g`, `carbs_g`, `fats_g`, `prep_time`, `cook_time`, `servings`, `ingredients_json`, `steps_json`, `mood_tags_json`, `views_count`) VALUES
('Comforting Chicken Noodle Soup', 'comforting-chicken-noodle-soup', 3, 'A warm, soothing bowl of chicken noodle soup that wraps you in comfort and helps melt away stress.', 'https://sc02.alicdn.com/kf/Hf8a7968638c6455a9109d0aa1da9d4dd9.png', 0, 1, 285, 22.0, 28.0, 9.5, 15, 45, 6,
'[{"qty": "1.5", "unit": "lbs", "item": "chicken thighs, bone-in"}, {"qty": "8", "unit": "cups", "item": "chicken broth"}, {"qty": "2", "unit": "cups", "item": "wide egg noodles"}, {"qty": "1", "unit": "large", "item": "onion, diced"}, {"qty": "3", "unit": "cloves", "item": "garlic, minced"}, {"qty": "2", "unit": "cups", "item": "carrots, sliced"}, {"qty": "1.5", "unit": "cups", "item": "celery, sliced"}, {"qty": "2", "unit": "tbsp", "item": "olive oil"}, {"qty": "1", "unit": "tsp", "item": "dried thyme"}, {"qty": "1", "unit": "tsp", "item": "dried rosemary"}, {"qty": "1", "unit": "bay leaf"}, {"qty": "1", "unit": "tsp", "item": "salt"}, {"qty": "1/2", "unit": "tsp", "item": "black pepper"}, {"qty": "1/4", "unit": "cup", "item": "fresh parsley, chopped"}]',
'[{"step": 1, "instruction": "Heat olive oil in a large pot over medium heat. Add onion and cook until translucent, about 5 minutes."}, {"step": 2, "instruction": "Add garlic, carrots, and celery. Cook for 5 minutes until vegetables begin to soften."}, {"step": 3, "instruction": "Add chicken thighs, broth, thyme, rosemary, bay leaf, salt, and pepper. Bring to a boil."}, {"step": 4, "instruction": "Reduce heat, cover, and simmer for 30 minutes until chicken is cooked through."}, {"step": 5, "instruction": "Remove chicken, shred meat, and return to pot. Add noodles and cook 8-10 minutes until tender. Garnish with parsley and serve hot."}]',
'["stressed"]', 445),

('Warm Mac and Cheese', 'warm-mac-and-cheese', 3, 'Creamy, cheesy macaroni that feels like a warm hug in a bowl - the ultimate comfort food for stressful days.', 'https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=800', 1, 0, 425, 18.0, 45.0, 18.0, 10, 25, 6,
'[{"qty": "1", "unit": "lb", "item": "elbow macaroni"}, {"qty": "4", "unit": "tbsp", "item": "butter"}, {"qty": "1/4", "unit": "cup", "item": "all-purpose flour"}, {"qty": "3", "unit": "cups", "item": "whole milk"}, {"qty": "3", "unit": "cups", "item": "cheddar cheese, shredded"}, {"qty": "1", "unit": "cup", "item": "mozzarella cheese, shredded"}, {"qty": "1/2", "unit": "cup", "item": "parmesan cheese, grated"}, {"qty": "1", "unit": "tsp", "item": "paprika"}, {"qty": "1/2", "unit": "tsp", "item": "mustard powder"}, {"qty": "1", "unit": "tsp", "item": "salt"}, {"qty": "1/2", "unit": "tsp", "item": "black pepper"}, {"qty": "1/2", "unit": "cup", "item": "breadcrumbs"}, {"qty": "2", "unit": "tbsp", "item": "butter for topping"}]',
'[{"step": 1, "instruction": "Preheat oven to 375°F. Cook macaroni according to package directions until al dente. Drain and set aside."}, {"step": 2, "instruction": "In a large pot, melt butter over medium heat. Whisk in flour and cook for 2 minutes to make a roux."}, {"step": 3, "instruction": "Gradually whisk in milk until smooth. Cook, stirring constantly, until sauce thickens, about 5 minutes."}, {"step": 4, "instruction": "Remove from heat. Stir in cheddar, mozzarella, and parmesan until melted. Add paprika, mustard, salt, and pepper."}, {"step": 5, "instruction": "Mix in cooked macaroni. Transfer to baking dish. Top with breadcrumbs mixed with melted butter. Bake 20 minutes until golden and bubbly."}]',
'["stressed"]', 389),

('Soothing Masala Chai', 'soothing-masala-chai', 2, 'A warm, spiced cup of chai that calms your nerves and brings peace to a stressful day.', 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800', 1, 0, 52, 1.5, 9.0, 1.8, 5, 12, 2,
'[{"qty": "2", "unit": "cups", "item": "water"}, {"qty": "2", "unit": "tbsp", "item": "black tea leaves"}, {"qty": "1", "unit": "cup", "item": "whole milk"}, {"qty": "1", "unit": "inch", "item": "fresh ginger, grated"}, {"qty": "4", "unit": "whole", "item": "cardamom pods, crushed"}, {"qty": "2", "unit": "whole", "item": "cinnamon sticks"}, {"qty": "4", "unit": "whole", "item": "cloves"}, {"qty": "6", "unit": "whole", "item": "black peppercorns"}, {"qty": "2", "unit": "tbsp", "item": "sugar"}, {"qty": "1", "unit": "pinch", "item": "nutmeg, grated"}]',
'[{"step": 1, "instruction": "In a saucepan, bring water to a boil. Add tea leaves, ginger, and all whole spices."}, {"step": 2, "instruction": "Reduce heat and simmer for 5 minutes to allow spices to infuse."}, {"step": 3, "instruction": "Add milk and sugar. Bring to a gentle boil, then reduce heat and simmer for 5 more minutes."}, {"step": 4, "instruction": "Strain the chai through a fine mesh sieve into cups."}, {"step": 5, "instruction": "Sprinkle with a pinch of nutmeg. Serve hot and take a moment to breathe and relax."}]',
'["stressed"]', 523),

('Hearty Beef Stew', 'hearty-beef-stew', 3, 'A rich, slow-cooked beef stew that provides deep comfort and warmth during stressful times.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-CzHb-TC0fxdkafQjaof3A1Q3Bf3XVMmd5A&s', 0, 1, 485, 38.0, 32.0, 22.0, 20, 120, 6,
'[{"qty": "2", "unit": "lbs", "item": "beef chuck, cut into cubes"}, {"qty": "2", "unit": "tbsp", "item": "olive oil"}, {"qty": "1", "unit": "large", "item": "onion, diced"}, {"qty": "4", "unit": "cloves", "item": "garlic, minced"}, {"qty": "3", "unit": "cups", "item": "beef broth"}, {"qty": "1", "unit": "cup", "item": "red wine"}, {"qty": "2", "unit": "cups", "item": "carrots, chopped"}, {"qty": "2", "unit": "cups", "item": "potatoes, cubed"}, {"qty": "1", "unit": "cup", "item": "celery, chopped"}, {"qty": "2", "unit": "tbsp", "item": "tomato paste"}, {"qty": "1", "unit": "tsp", "item": "dried thyme"}, {"qty": "2", "unit": "bay leaves"}, {"qty": "1", "unit": "tsp", "item": "salt"}, {"qty": "1/2", "unit": "tsp", "item": "black pepper"}, {"qty": "2", "unit": "tbsp", "item": "all-purpose flour"}]',
'[{"step": 1, "instruction": "Season beef cubes with salt and pepper. Dredge in flour. Heat oil in a large Dutch oven over high heat."}, {"step": 2, "instruction": "Brown beef cubes on all sides, working in batches. Remove and set aside."}, {"step": 3, "instruction": "Add onion to the pot and cook until soft. Add garlic and cook for 1 minute."}, {"step": 4, "instruction": "Return beef to pot. Add broth, wine, tomato paste, thyme, and bay leaves. Bring to a boil, then reduce heat."}, {"step": 5, "instruction": "Cover and simmer for 1.5 hours. Add carrots, potatoes, and celery. Continue simmering for 45 minutes until vegetables are tender. Serve hot."}]',
'["stressed"]', 367),

('Comforting Dal Bhat', 'comforting-dal-bhat', 1, 'Traditional Nepali comfort food - warm, hearty lentils and rice that soothe the soul and reduce stress.', 'https://punguskitchen.com/wp-content/uploads/2025/05/Dal-Bhat-with-Rice-and-Tadka.jpg', 1, 1, 445, 18.5, 68.0, 9.2, 10, 35, 2,
'[{"qty": "1", "unit": "cup", "item": "red lentils (masoor dal)"}, {"qty": "1", "unit": "cup", "item": "basmati rice"}, {"qty": "1", "unit": "large", "item": "onion, finely chopped"}, {"qty": "3", "unit": "cloves", "item": "garlic, minced"}, {"qty": "1", "unit": "inch", "item": "ginger, grated"}, {"qty": "2", "unit": "tbsp", "item": "ghee or oil"}, {"qty": "1", "unit": "tsp", "item": "turmeric powder"}, {"qty": "1", "unit": "tsp", "item": "cumin seeds"}, {"qty": "1", "unit": "tsp", "item": "coriander powder"}, {"qty": "1/2", "unit": "tsp", "item": "red chili powder"}, {"qty": "4", "unit": "cups", "item": "water"}, {"qty": "2", "unit": "tbsp", "item": "fresh cilantro, chopped"}, {"qty": "1", "unit": "tsp", "item": "salt"}]',
'[{"step": 1, "instruction": "Rinse lentils and rice separately until water runs clear. Set aside."}, {"step": 2, "instruction": "Cook rice: Bring 2 cups water to boil, add rice, cover, and simmer 15-18 minutes until fluffy."}, {"step": 3, "instruction": "For dal: Heat ghee in a pot. Add cumin seeds, let splutter. Add onion and cook until golden."}, {"step": 4, "instruction": "Add garlic, ginger, and all spices. Stir for 30 seconds. Add lentils and 2 cups water."}, {"step": 5, "instruction": "Bring to boil, reduce heat, cover and simmer 20-25 minutes until lentils are soft. Stir in cilantro. Serve dal over rice."}]',
'["stressed"]', 412),

('Warm Chocolate Chip Cookies', 'warm-chocolate-chip-cookies', 3, 'Freshly baked, warm chocolate chip cookies that provide instant comfort and stress relief.', 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800', 1, 0, 152, 2.2, 19.0, 7.8, 15, 12, 24,
'[{"qty": "2.25", "unit": "cups", "item": "all-purpose flour"}, {"qty": "1", "unit": "tsp", "item": "baking soda"}, {"qty": "1", "unit": "tsp", "item": "salt"}, {"qty": "1", "unit": "cup", "item": "butter, softened"}, {"qty": "3/4", "unit": "cup", "item": "granulated sugar"}, {"qty": "3/4", "unit": "cup", "item": "brown sugar"}, {"qty": "2", "unit": "large", "item": "eggs"}, {"qty": "2", "unit": "tsp", "item": "vanilla extract"}, {"qty": "2", "unit": "cups", "item": "chocolate chips"}]',
'[{"step": 1, "instruction": "Preheat oven to 375°F. Line baking sheets with parchment paper."}, {"step": 2, "instruction": "Whisk together flour, baking soda, and salt in a medium bowl."}, {"step": 3, "instruction": "In a large bowl, cream butter and both sugars until light and fluffy, about 3 minutes."}, {"step": 4, "instruction": "Beat in eggs one at a time, then vanilla. Gradually mix in flour mixture until just combined."}, {"step": 5, "instruction": "Stir in chocolate chips. Drop rounded tablespoons onto baking sheets. Bake 9-11 minutes until edges are golden. Enjoy warm!"}]',
'["stressed"]', 445),

('Cozy Potato Soup', 'cozy-potato-soup', 3, 'A creamy, comforting potato soup that feels like a warm blanket on a stressful day.', 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800', 1, 0, 285, 8.0, 42.0, 10.5, 15, 35, 6,
'[{"qty": "6", "unit": "large", "item": "potatoes, peeled and diced"}, {"qty": "1", "unit": "large", "item": "onion, diced"}, {"qty": "4", "unit": "cloves", "item": "garlic, minced"}, {"qty": "4", "unit": "cups", "item": "vegetable broth"}, {"qty": "2", "unit": "cups", "item": "whole milk"}, {"qty": "3", "unit": "tbsp", "item": "butter"}, {"qty": "1", "unit": "tsp", "item": "dried thyme"}, {"qty": "1/2", "unit": "tsp", "item": "paprika"}, {"qty": "1", "unit": "tsp", "item": "salt"}, {"qty": "1/2", "unit": "tsp", "item": "black pepper"}, {"qty": "1/2", "unit": "cup", "item": "cheddar cheese, shredded"}, {"qty": "4", "unit": "strips", "item": "bacon, cooked and crumbled (optional)"}, {"qty": "2", "unit": "tbsp", "item": "chives, chopped"}]',
'[{"step": 1, "instruction": "Melt butter in a large pot over medium heat. Add onion and cook until soft, about 5 minutes."}, {"step": 2, "instruction": "Add garlic and cook for 1 minute. Add potatoes, broth, thyme, paprika, salt, and pepper."}, {"step": 3, "instruction": "Bring to a boil, then reduce heat and simmer for 20-25 minutes until potatoes are tender."}, {"step": 4, "instruction": "Use an immersion blender to puree soup until smooth (or blend in batches)."}, {"step": 5, "instruction": "Stir in milk and heat through. Serve hot, topped with cheddar cheese, bacon, and chives."}]',
'["stressed"]', 298),

('Soothing Chamomile Tea', 'soothing-chamomile-tea', 7, 'A calming herbal tea that helps reduce stress and promotes relaxation after a long day.', 'https://images-prod.healthline.com/hlcmsresource/images/chamomile-tea.jpg', 1, 0, 3, 0.1, 0.5, 0.0, 3, 8, 1,
'[{"qty": "2", "unit": "tsp", "item": "dried chamomile flowers"}, {"qty": "1", "unit": "cup", "item": "boiling water"}, {"qty": "1", "unit": "tsp", "item": "honey (optional)"}, {"qty": "1", "unit": "slice", "item": "lemon (optional)"}, {"qty": "1", "unit": "sprig", "item": "fresh mint (optional)"}]',
'[{"step": 1, "instruction": "Place chamomile flowers in a tea infuser or teapot."}, {"step": 2, "instruction": "Pour boiling water over the chamomile. Cover and let steep for 5-8 minutes."}, {"step": 3, "instruction": "Remove the infuser or strain the tea."}, {"step": 4, "instruction": "Add honey and a slice of lemon if desired. Garnish with fresh mint."}, {"step": 5, "instruction": "Sip slowly, take deep breaths, and allow the calming properties to work their magic."}]',
'["stressed"]', 389),

('Comforting Shepherd\'s Pie', 'comforting-shepherds-pie', 3, 'A hearty, traditional shepherd\'s pie with savory meat and creamy mashed potatoes - ultimate comfort food.', 'https://www.thespruceeats.com/thmb/wtvhJGmmm79FRtZZ5ZCvEEKgzl4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/vegan-shepherds-pie-recipe-3377184-b90c677cb879468280b1a5a82ea59dc5.jpg', 0, 1, 485, 28.0, 38.0, 22.0, 25, 45, 6,
'[{"qty": "1.5", "unit": "lbs", "item": "ground lamb or beef"}, {"qty": "1", "unit": "large", "item": "onion, diced"}, {"qty": "2", "unit": "cloves", "item": "garlic, minced"}, {"qty": "2", "unit": "cups", "item": "mixed vegetables (peas, carrots, corn)"}, {"qty": "2", "unit": "tbsp", "item": "tomato paste"}, {"qty": "1", "unit": "cup", "item": "beef broth"}, {"qty": "1", "unit": "tsp", "item": "Worcestershire sauce"}, {"qty": "2", "unit": "lbs", "item": "potatoes, peeled and cubed"}, {"qty": "4", "unit": "tbsp", "item": "butter"}, {"qty": "1/2", "unit": "cup", "item": "milk"}, {"qty": "1/2", "unit": "cup", "item": "cheddar cheese, shredded"}, {"qty": "1", "unit": "tsp", "item": "salt"}, {"qty": "1/2", "unit": "tsp", "item": "black pepper"}]',
'[{"step": 1, "instruction": "Preheat oven to 400°F. Cook potatoes in boiling water until tender, about 15 minutes."}, {"step": 2, "instruction": "Meanwhile, brown ground meat in a large skillet. Add onion and garlic, cook until soft."}, {"step": 3, "instruction": "Add vegetables, tomato paste, broth, and Worcestershire sauce. Simmer 10 minutes until thickened."}, {"step": 4, "instruction": "Mash potatoes with butter and milk. Season with salt and pepper."}, {"step": 5, "instruction": "Transfer meat mixture to baking dish. Top with mashed potatoes. Sprinkle with cheese. Bake 25 minutes until golden."}]',
'["stressed"]', 334),

('Warm Apple Cinnamon Oatmeal', 'warm-apple-cinnamon-oatmeal', 3, 'A comforting bowl of warm oatmeal with sweet apples and cinnamon - a soothing start to any stressful day.', 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800', 1, 0, 285, 8.5, 52.0, 6.5, 5, 15, 2,
'[{"qty": "1", "unit": "cup", "item": "rolled oats"}, {"qty": "2", "unit": "cups", "item": "milk or water"}, {"qty": "1", "unit": "large", "item": "apple, peeled and diced"}, {"qty": "1", "unit": "tsp", "item": "ground cinnamon"}, {"qty": "1/4", "unit": "tsp", "item": "nutmeg"}, {"qty": "2", "unit": "tbsp", "item": "brown sugar"}, {"qty": "1", "unit": "tbsp", "item": "butter"}, {"qty": "1/4", "unit": "cup", "item": "walnuts, chopped"}, {"qty": "1", "unit": "tbsp", "item": "maple syrup"}]',
'[{"step": 1, "instruction": "In a medium saucepan, bring milk or water to a boil. Add oats and reduce heat to low."}, {"step": 2, "instruction": "Stir in diced apple, cinnamon, and nutmeg. Cook for 10-12 minutes, stirring occasionally."}, {"step": 3, "instruction": "When oats are creamy and apple is tender, stir in brown sugar and butter."}, {"step": 4, "instruction": "Remove from heat and let stand for 2 minutes."}, {"step": 5, "instruction": "Serve warm, topped with chopped walnuts and a drizzle of maple syrup. Enjoy the comforting warmth."}]',
'["stressed"]', 256),





('Warm Chicken Soup', 'warm-chicken-soup', 3, 'Hearty, nourishing soup that wraps you in comfort and warmth.', 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800', 0, 1, 250, 22.0, 15.0, 10.0, 15, 45, 4,
'[{"qty": "1", "unit": "lb", "item": "chicken breast, diced"}, {"qty": "6", "unit": "cups", "item": "chicken broth"}, {"qty": "2", "unit": "cups", "item": "mixed vegetables"}, {"qty": "1", "unit": "cup", "item": "egg noodles"}, {"qty": "2", "unit": "cloves", "item": "garlic"}, {"qty": "1", "unit": "tsp", "item": "thyme"}]',
'[{"step": 1, "instruction": "Sauté chicken until cooked through."}, {"step": 2, "instruction": "Add broth, vegetables, and seasonings. Simmer 30 minutes."}, {"step": 3, "instruction": "Add noodles and cook until tender. Serve hot."}]',
'["stressed"]', 124),

('Comfort Mac and Cheese', 'comfort-mac-and-cheese', 3, 'Creamy, cheesy pasta that feels like a warm hug in a bowl.', 'https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=800', 1, 0, 380, 15.0, 42.0, 16.0, 10, 20, 4,
'[{"qty": "1", "unit": "lb", "item": "elbow macaroni"}, {"qty": "3", "unit": "cups", "item": "cheddar cheese, shredded"}, {"qty": "2", "unit": "cups", "item": "milk"}, {"qty": "3", "unit": "tbsp", "item": "butter"}, {"qty": "3", "unit": "tbsp", "item": "flour"}, {"qty": "1", "unit": "tsp", "item": "paprika"}]',
'[{"step": 1, "instruction": "Cook pasta according to package directions."}, {"step": 2, "instruction": "Make roux with butter and flour, add milk for béchamel."}, {"step": 3, "instruction": "Stir in cheese until melted. Mix with pasta and bake until golden."}]',
'["stressed"]', 98);

-- Tired Mood Recipes
INSERT INTO `recipes` (`title`, `slug`, `cuisine_id`, `description`, `image_url`, `is_veg`, `is_high_protein`, `calories`, `proteins_g`, `carbs_g`, `fats_g`, `prep_time`, `cook_time`, `servings`, `ingredients_json`, `steps_json`, `mood_tags_json`, `views_count`) VALUES
('Energy-Boosting Chicken Curry', 'energy-boosting-chicken-curry', 2, 'Protein-packed curry with spices that wake up your senses and fuel your body!', 'https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/chicken_curry_61994_16x9.jpg', 0, 1, 450, 35.0, 25.0, 22.0, 15, 35, 3,
'[{"qty": "1.5", "unit": "lbs", "item": "chicken thighs"}, {"qty": "1", "unit": "cup", "item": "coconut milk"}, {"qty": "2", "unit": "tbsp", "item": "curry powder"}, {"qty": "1", "unit": "onion", "item": "diced"}, {"qty": "3", "unit": "cloves", "item": "garlic"}, {"qty": "1", "unit": "tbsp", "item": "ginger paste"}]',
'[{"step": 1, "instruction": "Sauté onions, garlic, and ginger until fragrant."}, {"step": 2, "instruction": "Add chicken and curry powder, cook until browned."}, {"step": 3, "instruction": "Pour in coconut milk, simmer 25 minutes until tender. Serve with rice."}]',
'["tired"]', 112),

('Protein Power Smoothie Bowl', 'protein-power-smoothie-bowl', 3, 'A vibrant, nutrient-dense bowl that recharges your energy in minutes!', 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800', 1, 1, 320, 28.0, 35.0, 8.0, 5, 0, 1,
'[{"qty": "1", "unit": "scoop", "item": "protein powder"}, {"qty": "1", "unit": "banana", "item": "frozen"}, {"qty": "1/2", "unit": "cup", "item": "Greek yogurt"}, {"qty": "1/2", "unit": "cup", "item": "almond milk"}, {"qty": "2", "unit": "tbsp", "item": "chia seeds"}, {"qty": "1/4", "unit": "cup", "item": "granola"}, {"qty": "1/4", "unit": "cup", "item": "fresh berries"}]',
'[{"step": 1, "instruction": "Blend protein powder, banana, yogurt, and milk until smooth."}, {"step": 2, "instruction": "Pour into bowl and top with chia seeds, granola, and berries."}]',
'["tired"]', 76),

('Revitalizing Ramen Bowl', 'revitalizing-ramen-bowl', 5, 'Hearty Japanese ramen with protein and complex carbs to power through your day!', 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800', 0, 1, 520, 32.0, 55.0, 15.0, 20, 15, 2,
'[{"qty": "2", "unit": "packages", "item": "ramen noodles"}, {"qty": "2", "unit": "eggs", "item": "soft-boiled"}, {"qty": "4", "unit": "oz", "item": "pork belly or chicken"}, {"qty": "4", "unit": "cups", "item": "broth"}, {"qty": "2", "unit": "cups", "item": "bok choy"}, {"qty": "2", "unit": "tbsp", "item": "soy sauce"}, {"qty": "1", "unit": "tbsp", "item": "sesame oil"}]',
'[{"step": 1, "instruction": "Cook noodles according to package. Soft-boil eggs."}, {"step": 2, "instruction": "Heat broth, add soy sauce and sesame oil."}, {"step": 3, "instruction": "Assemble: noodles in bowl, pour hot broth, top with meat, bok choy, and egg."}]',
'["tired"]', 143),

('Quick Energy Omelette', 'quick-energy-omelette', 3, 'High-protein omelette loaded with veggies - ready in 10 minutes to fuel your day!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTbnh5a6QOXaIR6FTPQ_XkvuwmZbwvTmuiqQ&s', 0, 1, 280, 22.0, 8.0, 18.0, 5, 8, 1,
'[{"qty": "3", "unit": "large", "item": "eggs"}, {"qty": "1/4", "unit": "cup", "item": "cheddar cheese"}, {"qty": "1/4", "unit": "cup", "item": "spinach"}, {"qty": "2", "unit": "tbsp", "item": "mushrooms, sliced"}, {"qty": "1", "unit": "tbsp", "item": "butter"}, {"qty": "1", "unit": "pinch", "item": "salt and pepper"}]',
'[{"step": 1, "instruction": "Whisk eggs with salt and pepper."}, {"step": 2, "instruction": "Heat butter in pan, pour eggs. Add fillings when bottom sets."}, {"step": 3, "instruction": "Fold omelette and cook until set. Serve immediately."}]',
'["tired"]', 91);

-- Multi-mood recipes
INSERT INTO `recipes` (`title`, `slug`, `cuisine_id`, `description`, `image_url`, `is_veg`, `is_high_protein`, `calories`, `proteins_g`, `carbs_g`, `fats_g`, `prep_time`, `cook_time`, `servings`, `ingredients_json`, `steps_json`, `mood_tags_json`, `views_count`) VALUES
('Espresso Delight', 'espresso-delight', 7, 'Rich, aromatic coffee that wakes you up and brings a smile - perfect for any mood!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmK9ltBgasM0eefEKUfrVkgK1HMHqnyfMr1g&s', 1, 0, 5, 0.3, 0.0, 0.0, 2, 3, 1,
'[{"qty": "1", "unit": "shot", "item": "espresso"}, {"qty": "1", "unit": "oz", "item": "steamed milk (optional)"}, {"qty": "1", "unit": "tsp", "item": "sugar (optional)"}]',
'[{"step": 1, "instruction": "Brew espresso shot."}, {"step": 2, "instruction": "Add steamed milk if desired (for cappuccino)."}, {"step": 3, "instruction": "Sweeten to taste and enjoy!"}]',
'["happy", "tired"]', 234),

('Momo', 'momo', 1, 'Steamed Nepali dumplings that bring joy and comfort in every bite!', 'https://tarasmulticulturaltable.com/wp-content/uploads/2019/07/Meat-Filled-Momos-9-of-10.jpg', 0, 1, 280, 18.0, 32.0, 8.0, 30, 20, 4,
'[{"qty": "1", "unit": "lb", "item": "ground chicken or pork"}, {"qty": "2", "unit": "cups", "item": "all-purpose flour"}, {"qty": "1/2", "unit": "cup", "item": "cabbage, finely chopped"}, {"qty": "2", "unit": "cloves", "item": "garlic, minced"}, {"qty": "1", "unit": "tbsp", "item": "ginger paste"}, {"qty": "1", "unit": "tsp", "item": "soy sauce"}]',
'[{"step": 1, "instruction": "Make dough from flour and water. Rest 30 minutes."}, {"step": 2, "instruction": "Mix filling ingredients. Fill and shape dumplings."}, {"step": 3, "instruction": "Steam for 15-20 minutes. Serve with spicy tomato chutney."}]',
'["happy", "stressed"]', 167),

('Sushi Platter', 'sushi-platter', 5, 'Fresh, colorful sushi that delights the eyes and energizes the body!', 'https://www.justonecookbook.com/wp-content/uploads/2020/01/Sushi-Rolls-Maki-Sushi-%E2%80%93-Hosomaki-1117-I.jpg', 0, 1, 350, 20.0, 45.0, 8.0, 40, 20, 2,
'[{"qty": "2", "unit": "cups", "item": "sushi rice"}, {"qty": "8", "unit": "sheets", "item": "nori"}, {"qty": "4", "unit": "oz", "item": "fresh salmon"}, {"qty": "1", "unit": "cucumber", "item": "julienned"}, {"qty": "1", "unit": "avocado", "item": "sliced"}, {"qty": "2", "unit": "tbsp", "item": "rice vinegar"}, {"qty": "1", "unit": "tbsp", "item": "wasabi"}]',
'[{"step": 1, "instruction": "Cook and season rice with vinegar. Let cool."}, {"step": 2, "instruction": "Place nori on bamboo mat, spread rice, add fillings."}, {"step": 3, "instruction": "Roll tightly, slice, and serve with soy sauce and wasabi."}]',
'["happy", "tired"]', 198),

('Margherita Pizza', 'margherita-pizza', 6, 'Classic Italian pizza with fresh basil and mozzarella – comforting and joyful.', 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Margherita_Originale.jpg', 1, 0, 520, 22.0, 62.0, 18.0, 30, 15, 2,
'[{"qty": "1", "unit": "piece", "item": "pizza dough"}, {"qty": "1/2", "unit": "cup", "item": "tomato sauce"}, {"qty": "150", "unit": "g", "item": "mozzarella cheese"}, {"qty": "10", "unit": "leaves", "item": "fresh basil"}, {"qty": "1", "unit": "tbsp", "item": "olive oil"}]',
'[{"step": 1, "instruction": "Preheat oven to highest temperature."}, {"step": 2, "instruction": "Spread sauce on dough, add mozzarella."}, {"step": 3, "instruction": "Bake until crust is golden."}, {"step": 4, "instruction": "Top with basil and olive oil. Serve hot."}]',
'["happy", "comfort"]', 102),

('Vegetable Fried Rice', 'vegetable-fried-rice', 4, 'Quick and flavorful fried rice that boosts mood and energy.', 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Fried_Rice_with_Egg_and_Vegetables.jpg', 1, 0, 380, 10.0, 58.0, 10.0, 15, 15, 2,
'[{"qty": "2", "unit": "cups", "item": "cooked rice"}, {"qty": "1", "unit": "cup", "item": "mixed vegetables"}, {"qty": "1", "unit": "tbsp", "item": "soy sauce"}, {"qty": "1", "unit": "tbsp", "item": "oil"}, {"qty": "1", "unit": "clove", "item": "garlic"}]',
'[{"step": 1, "instruction": "Heat oil and sauté garlic."}, {"step": 2, "instruction": "Add vegetables and stir-fry."}, {"step": 3, "instruction": "Add rice and soy sauce, mix well."}, {"step": 4, "instruction": "Cook 2–3 minutes and serve."}]',
'["tired", "stressed"]', 86),

('Pancakes', 'classic-pancakes', 7, 'Fluffy pancakes that instantly lift your mood and satisfy cravings.', 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Stack_of_pancakes.jpg', 1, 0, 450, 9.0, 65.0, 14.0, 10, 15, 2,
'[{"qty": "1", "unit": "cup", "item": "all-purpose flour"}, {"qty": "1", "unit": "cup", "item": "milk"}, {"qty": "1", "unit": "egg", "item": "egg"}, {"qty": "1", "unit": "tbsp", "item": "sugar"}, {"qty": "1", "unit": "tsp", "item": "baking powder"}]',
'[{"step": 1, "instruction": "Mix dry ingredients."}, {"step": 2, "instruction": "Whisk in milk and egg."}, {"step": 3, "instruction": "Pour batter onto hot pan."}, {"step": 4, "instruction": "Cook until golden on both sides."}]',
'["happy", "lazy"]', 143),

('Grilled Chicken Salad', 'grilled-chicken-salad', 5, 'Light yet satisfying salad that refreshes the mind and body.', 'https://upload.wikimedia.org/wikipedia/commons/7/75/Chicken_salad.jpg', 0, 1, 320, 30.0, 12.0, 14.0, 15, 15, 2,
'[{"qty": "200", "unit": "g", "item": "chicken breast"}, {"qty": "2", "unit": "cups", "item": "mixed greens"}, {"qty": "1", "unit": "tbsp", "item": "olive oil"}, {"qty": "1", "unit": "tbsp", "item": "lemon juice"}, {"qty": "to taste", "unit": "", "item": "salt and pepper"}]',
'[{"step": 1, "instruction": "Season and grill chicken until cooked."}, {"step": 2, "instruction": "Slice chicken."}, {"step": 3, "instruction": "Toss greens with dressing."}, {"step": 4, "instruction": "Top with chicken and serve."}]',
'["energetic", "focused"]', 69);



-- Bored Mood Recipes
INSERT INTO `recipes` (`title`, `slug`, `cuisine_id`, `description`, `image_url`, `is_veg`, `is_high_protein`, `calories`, `proteins_g`, `carbs_g`, `fats_g`, `prep_time`, `cook_time`, `servings`, `ingredients_json`, `steps_json`, `mood_tags_json`, `views_count`) VALUES
('Fusion Tacos with Kimchi', 'fusion-tacos-kimchi', 4, 'A playful fusion of Mexican and Korean flavors - crispy tacos filled with spicy kimchi and fresh veggies!', 'https://howtofeedaloon.com/wp-content/uploads/2025/01/korean-Beef-Tacos-overhead.jpg', 1, 0, 320, 12.0, 45.0, 10.0, 20, 15, 3,
'[{"qty": "6", "unit": "pieces", "item": "corn tortillas"}, {"qty": "1", "unit": "cup", "item": "kimchi, chopped"}, {"qty": "1", "unit": "cup", "item": "black beans, cooked"}, {"qty": "1/2", "unit": "cup", "item": "red cabbage, shredded"}, {"qty": "1/4", "unit": "cup", "item": "cilantro"}, {"qty": "2", "unit": "tbsp", "item": "lime juice"}, {"qty": "1", "unit": "avocado", "item": "sliced"}, {"qty": "2", "unit": "tbsp", "item": "sriracha mayo"}]',
'[{"step": 1, "instruction": "Warm tortillas in a dry pan until slightly crispy."}, {"step": 2, "instruction": "Mix kimchi with black beans and season with lime juice."}, {"step": 3, "instruction": "Fill tortillas with kimchi mixture, top with cabbage, avocado, cilantro, and drizzle with sriracha mayo."}]',
'["bored"]', 42),

('Rainbow Buddha Bowl', 'rainbow-buddha-bowl', 3, 'A colorful, Instagram-worthy bowl with vibrant veggies, grains, and creative toppings that spark joy!', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800', 1, 1, 380, 18.0, 55.0, 12.0, 25, 0, 1,
'[{"qty": "1", "unit": "cup", "item": "quinoa, cooked"}, {"qty": "1/2", "unit": "cup", "item": "chickpeas, roasted"}, {"qty": "1/2", "unit": "cup", "item": "sweet potato, roasted"}, {"qty": "1/4", "unit": "cup", "item": "red bell pepper, sliced"}, {"qty": "1/4", "unit": "cup", "item": "purple cabbage, shredded"}, {"qty": "1/4", "unit": "cup", "item": "carrots, spiralized"}, {"qty": "2", "unit": "tbsp", "item": "tahini dressing"}, {"qty": "1", "unit": "tbsp", "item": "pumpkin seeds"}, {"qty": "1", "unit": "tbsp", "item": "goji berries"}]',
'[{"step": 1, "instruction": "Arrange quinoa as base in a large bowl."}, {"step": 2, "instruction": "Artistically place colorful vegetables in sections around the bowl."}, {"step": 3, "instruction": "Top with roasted chickpeas, drizzle tahini dressing, and garnish with seeds and goji berries."}]',
'["bored"]', 58),

('Sushi Burrito Fusion', 'sushi-burrito-fusion', 5, 'A fun, oversized sushi roll wrapped like a burrito - perfect for breaking the monotony!', 'https://www.sidechef.com/recipe/0fbd70b3-d17d-4928-952f-80f4ebf19c6f.jpg?d=1408x1120', 0, 1, 450, 22.0, 65.0, 12.0, 30, 10, 1,
'[{"qty": "1", "unit": "cup", "item": "sushi rice, cooked"}, {"qty": "1", "unit": "sheet", "item": "nori, large"}, {"qty": "3", "unit": "oz", "item": "salmon, sliced"}, {"qty": "1/4", "unit": "cup", "item": "cucumber, julienned"}, {"qty": "1/4", "unit": "cup", "item": "avocado, sliced"}, {"qty": "1/4", "unit": "cup", "item": "mango, sliced"}, {"qty": "2", "unit": "tbsp", "item": "spicy mayo"}, {"qty": "1", "unit": "tbsp", "item": "sesame seeds"}]',
'[{"step": 1, "instruction": "Lay nori sheet on bamboo mat. Spread sushi rice evenly, leaving edges."}, {"step": 2, "instruction": "Arrange salmon, cucumber, avocado, and mango in center."}, {"step": 3, "instruction": "Roll tightly like a burrito, slice in half, drizzle with spicy mayo and sprinkle sesame seeds."}]',
'["bored"]', 67);

-- Romantic Mood Recipes
INSERT INTO `recipes` (`title`, `slug`, `cuisine_id`, `description`, `image_url`, `is_veg`, `is_high_protein`, `calories`, `proteins_g`, `carbs_g`, `fats_g`, `prep_time`, `cook_time`, `servings`, `ingredients_json`, `steps_json`, `mood_tags_json`, `views_count`) VALUES
('Creamy Mushroom Risotto', 'creamy-mushroom-risotto', 6, 'Rich, velvety risotto with earthy mushrooms - perfect for a cozy, candlelit dinner for two!', 'https://i0.wp.com/cookingitalians.com/wp-content/uploads/2025/04/image.jpeg?fit=1152%2C864&ssl=1', 1, 0, 420, 12.0, 58.0, 16.0, 15, 30, 2,
'[{"qty": "1", "unit": "cup", "item": "arborio rice"}, {"qty": "8", "unit": "oz", "item": "mixed mushrooms, sliced"}, {"qty": "4", "unit": "cups", "item": "vegetable broth, warm"}, {"qty": "1/2", "unit": "cup", "item": "white wine"}, {"qty": "1/4", "unit": "cup", "item": "parmesan cheese, grated"}, {"qty": "2", "unit": "tbsp", "item": "butter"}, {"qty": "2", "unit": "cloves", "item": "garlic, minced"}, {"qty": "1", "unit": "tbsp", "item": "fresh thyme"}, {"qty": "1", "unit": "tbsp", "item": "truffle oil (optional)"}]',
'[{"step": 1, "instruction": "Sauté mushrooms in butter until golden. Set aside."}, {"step": 2, "instruction": "In same pan, toast rice, add wine and stir until absorbed."}, {"step": 3, "instruction": "Add warm broth one ladle at a time, stirring constantly for 20-25 minutes until creamy."}, {"step": 4, "instruction": "Stir in mushrooms, parmesan, thyme, and truffle oil. Serve immediately."}]',
'["romantic"]', 89),

('Chocolate Lava Cake', 'chocolate-lava-cake', 3, 'Decadent, warm chocolate cake with a molten center - the ultimate romantic dessert!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGq_KXkLbSTc7Joi0D1LjS0mS7EhyjRVh9LQ&s', 1, 0, 480, 6.0, 52.0, 28.0, 15, 12, 2,
'[{"qty": "4", "unit": "oz", "item": "dark chocolate, chopped"}, {"qty": "4", "unit": "tbsp", "item": "butter"}, {"qty": "2", "unit": "large", "item": "eggs"}, {"qty": "2", "unit": "tbsp", "item": "sugar"}, {"qty": "2", "unit": "tbsp", "item": "flour"}, {"qty": "1", "unit": "tsp", "item": "vanilla extract"}, {"qty": "1", "unit": "pinch", "item": "salt"}, {"qty": "2", "unit": "scoops", "item": "vanilla ice cream"}]',
'[{"step": 1, "instruction": "Preheat oven to 425°F. Melt chocolate and butter in double boiler."}, {"step": 2, "instruction": "Whisk eggs, sugar, and vanilla. Fold in chocolate mixture and flour."}, {"step": 3, "instruction": "Pour into buttered ramekins, bake 10-12 minutes until edges set but center is soft."}, {"step": 4, "instruction": "Invert onto plates, serve immediately with vanilla ice cream."}]',
'["romantic"]', 124),

('Strawberry Panna Cotta', 'strawberry-panna-cotta', 6, 'Silky, elegant Italian dessert with fresh strawberries - beautiful and romantic!', 'https://vjcooks.com/wp-content/uploads/2022/12/IMG_6104-scaled-720x720.jpg', 1, 0, 220, 4.0, 28.0, 10.0, 20, 0, 2,
'[{"qty": "2", "unit": "cups", "item": "heavy cream"}, {"qty": "1/2", "unit": "cup", "item": "sugar"}, {"qty": "2", "unit": "tsp", "item": "vanilla extract"}, {"qty": "2", "unit": "tsp", "item": "gelatin powder"}, {"qty": "1", "unit": "cup", "item": "fresh strawberries, sliced"}, {"qty": "2", "unit": "tbsp", "item": "honey"}, {"qty": "1", "unit": "tsp", "item": "lemon zest"}]',
'[{"step": 1, "instruction": "Heat cream and sugar until sugar dissolves. Remove from heat."}, {"step": 2, "instruction": "Bloom gelatin in cold water, then whisk into warm cream with vanilla."}, {"step": 3, "instruction": "Pour into serving glasses, chill 4 hours until set."}, {"step": 4, "instruction": "Top with fresh strawberries, drizzle honey, and garnish with lemon zest."}]',
'["romantic"]', 76),

('Garlic Butter Shrimp Pasta', 'garlic-butter-shrimp-pasta', 6, 'Silky pasta tossed with garlic butter shrimp and a hint of lemon – elegant yet simple for a romantic dinner.' ,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDkx83_EPFSanZzwqGktdUajfxrW_C_kp2mg&s', 0, 1, 510, 28.0, 54.0, 22.0, 15, 20, 2,
'[{"qty": "200", "unit": "g", "item": "spaghetti"}, {"qty": "250", "unit": "g", "item": "shrimp, peeled and deveined"}, {"qty": "3", "unit": "tbsp", "item": "butter"}, {"qty": "4", "unit": "cloves", "item": "garlic, minced"}, {"qty": "1", "unit": "tbsp", "item": "lemon juice"}, {"qty": "1/4", "unit": "cup", "item": "parmesan cheese, grated"}, {"qty": "to taste", "unit": "", "item": "salt and pepper"}, {"qty": "2", "unit": "tbsp", "item": "fresh parsley, chopped"}]',
'[{"step": 1, "instruction": "Cook pasta according to package instructions. Reserve some pasta water."}, {"step": 2, "instruction": "Sauté garlic in butter, add shrimp and cook until pink."}, {"step": 3, "instruction": "Add cooked pasta, lemon juice, and a splash of pasta water."}, {"step": 4, "instruction": "Toss with parmesan and parsley. Serve warm."}]',
'["romantic"]', 61),

('Red Wine Braised Chicken', 'red-wine-braised-chicken', 4, 'Tender chicken slowly braised in red wine with herbs – deeply flavorful and perfect for date night.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKRVtla33fbyzdYe7YN-QjvU4rMqbuHcKe-A&s', 0, 1, 460, 32.0, 18.0, 26.0, 20, 45, 2,
'[{"qty": "2", "unit": "pieces", "item": "chicken thighs"}, {"qty": "1", "unit": "cup", "item": "red wine"}, {"qty": "1", "unit": "cup", "item": "chicken stock"}, {"qty": "1", "unit": "tbsp", "item": "olive oil"}, {"qty": "1", "unit": "small", "item": "onion, sliced"}, {"qty": "2", "unit": "cloves", "item": "garlic"}, {"qty": "1", "unit": "tsp", "item": "fresh rosemary"}, {"qty": "to taste", "unit": "", "item": "salt and pepper"}]',
'[{"step": 1, "instruction": "Season chicken and sear in olive oil until browned."}, {"step": 2, "instruction": "Add onion and garlic, cook until soft."}, {"step": 3, "instruction": "Pour in red wine and stock, add rosemary."}, {"step": 4, "instruction": "Cover and simmer 40 minutes until chicken is tender."}]',
'["romantic"]', 48),

('Caprese Stuffed Avocados', 'caprese-stuffed-avocados', 5, 'Fresh avocados stuffed with mozzarella, tomatoes, and basil – light, fresh, and romantic.', 'https://www.eatingwell.com/thmb/YZ1R9b0qfZ4m.jpg', 1, 0, 290, 8.0, 14.0, 22.0, 10, 0, 2,
'[{"qty": "2", "unit": "large", "item": "avocados"}, {"qty": "1/2", "unit": "cup", "item": "cherry tomatoes, chopped"}, {"qty": "1/2", "unit": "cup", "item": "fresh mozzarella, diced"}, {"qty": "1", "unit": "tbsp", "item": "olive oil"}, {"qty": "1", "unit": "tbsp", "item": "balsamic glaze"}, {"qty": "to taste", "unit": "", "item": "salt and pepper"}, {"qty": "2", "unit": "tbsp", "item": "fresh basil, chopped"}]',
'[{"step": 1, "instruction": "Cut avocados in half and remove pits."}, {"step": 2, "instruction": "Mix tomatoes, mozzarella, basil, olive oil, salt, and pepper."}, {"step": 3, "instruction": "Spoon mixture into avocado halves."}, {"step": 4, "instruction": "Drizzle with balsamic glaze and serve."}]',
'["romantic"]', 37),

('Rose Milk Dessert', 'rose-milk-dessert', 7, 'Chilled, fragrant rose-flavored milk dessert – delicate, soothing, and romantic.', 'https://www.rodellekitchen.com/wp-content/uploads/2023/06/ALH04062-Hero-jpg.webp', 1, 0, 180, 5.0, 24.0, 6.0, 5, 0, 2,
'[{"qty": "2", "unit": "cups", "item": "cold milk"}, {"qty": "2", "unit": "tbsp", "item": "rose syrup"}, {"qty": "1", "unit": "tbsp", "item": "sugar"}, {"qty": "1", "unit": "tbsp", "item": "chopped pistachios"}, {"qty": "1", "unit": "tsp", "item": "rose petals (optional)"}]',
'[{"step": 1, "instruction": "Mix milk, rose syrup, and sugar until dissolved."}, {"step": 2, "instruction": "Chill for 15 minutes."}, {"step": 3, "instruction": "Pour into serving glasses."}, {"step": 4, "instruction": "Garnish with pistachios and rose petals before serving."}]',
'["romantic"]', 52);



-- Angry Mood Recipes
INSERT INTO `recipes` (`title`, `slug`, `cuisine_id`, `description`, `image_url`, `is_veg`, `is_high_protein`, `calories`, `proteins_g`, `carbs_g`, `fats_g`, `prep_time`, `cook_time`, `servings`, `ingredients_json`, `steps_json`, `mood_tags_json`, `views_count`) VALUES
('Spicy Sichuan Noodles', 'spicy-sichuan-noodles', 4, 'Fiery, numbing Sichuan noodles that pack a punch - perfect for releasing tension!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbGRgxiCViJawRKkM_mQsjVvk0R5YEEMEu6w&s', 1, 0, 380, 12.0, 58.0, 14.0, 10, 15, 2,
'[{"qty": "8", "unit": "oz", "item": "wheat noodles"}, {"qty": "3", "unit": "tbsp", "item": "Sichuan peppercorns"}, {"qty": "4", "unit": "tbsp", "item": "chili oil"}, {"qty": "2", "unit": "tbsp", "item": "soy sauce"}, {"qty": "2", "unit": "tbsp", "item": "black vinegar"}, {"qty": "1", "unit": "tbsp", "item": "ginger, minced"}, {"qty": "3", "unit": "cloves", "item": "garlic, minced"}, {"qty": "2", "unit": "tbsp", "item": "peanut butter"}, {"qty": "1/4", "unit": "cup", "item": "scallions, chopped"}, {"qty": "1/4", "unit": "cup", "item": "cilantro"}]',
'[{"step": 1, "instruction": "Toast Sichuan peppercorns until fragrant, grind to powder."}, {"step": 2, "instruction": "Cook noodles according to package. Drain and set aside."}, {"step": 3, "instruction": "Mix chili oil, soy sauce, vinegar, ginger, garlic, and peanut butter for sauce."}, {"step": 4, "instruction": "Toss noodles with sauce, sprinkle with peppercorn powder, scallions, and cilantro. Serve hot!"}]',
'["angry"]', 112),

('Crispy Buffalo Cauliflower', 'crispy-buffalo-cauliflower', 3, 'Crunchy, spicy buffalo cauliflower bites that satisfy the need for something bold and fiery!', 'https://www.seriouseats.com/thmb/uvJBMa16RPq1t1EJsNm-7-3gSek=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2013__02__20180315-buffalo-cauliflower-vicky-wasik-8-5c91622f7bcf47fbbdfaa00f23b39db0.jpg', 1, 0, 280, 8.0, 35.0, 12.0, 15, 25, 3,
'[{"qty": "1", "unit": "head", "item": "cauliflower, cut into florets"}, {"qty": "1", "unit": "cup", "item": "all-purpose flour"}, {"qty": "1", "unit": "cup", "item": "water"}, {"qty": "1", "unit": "tsp", "item": "garlic powder"}, {"qty": "1", "unit": "tsp", "item": "paprika"}, {"qty": "1/2", "unit": "cup", "item": "buffalo sauce"}, {"qty": "2", "unit": "tbsp", "item": "butter, melted"}, {"qty": "1/4", "unit": "cup", "item": "blue cheese dressing"}]',
'[{"step": 1, "instruction": "Preheat oven to 450°F. Mix flour, water, and spices for batter."}, {"step": 2, "instruction": "Dip cauliflower in batter, place on baking sheet. Bake 20 minutes until crispy."}, {"step": 3, "instruction": "Mix buffalo sauce with butter. Toss cauliflower in sauce."}, {"step": 4, "instruction": "Return to oven for 5 minutes. Serve with blue cheese dressing."}]',
'["angry"]', 98),

('Fiery Chicken Vindaloo', 'fiery-chicken-vindaloo', 2, 'Intensely spicy Goan curry that burns away frustration - not for the faint of heart!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6hiJX3DI25uEdO72WQ9Mo4yNfReva8_fj-g&s', 0, 1, 450, 35.0, 25.0, 22.0, 20, 40, 3,
'[{"qty": "1.5", "unit": "lbs", "item": "chicken thighs, cut"}, {"qty": "6", "unit": "dried red chilies"}, {"qty": "1", "unit": "tbsp", "item": "cumin seeds"}, {"qty": "1", "unit": "tbsp", "item": "coriander seeds"}, {"qty": "1", "unit": "tsp", "item": "turmeric"}, {"qty": "1", "unit": "tsp", "item": "mustard seeds"}, {"qty": "4", "unit": "cloves", "item": "garlic"}, {"qty": "1", "unit": "inch", "item": "ginger"}, {"qty": "3", "unit": "tbsp", "item": "white vinegar"}, {"qty": "1", "unit": "onion", "item": "diced"}, {"qty": "1", "unit": "cup", "item": "coconut milk"}]',
'[{"step": 1, "instruction": "Soak chilies in vinegar. Grind with spices, garlic, and ginger to make paste."}, {"step": 2, "instruction": "Marinate chicken in paste for 30 minutes."}, {"step": 3, "instruction": "Sauté onions until golden. Add chicken and cook until browned."}, {"step": 4, "instruction": "Add coconut milk, simmer 30 minutes until chicken is tender and sauce is thick. Serve with rice."}]',
'["angry"]', 143);

-- Relaxed Mood Recipes
INSERT INTO `recipes` (`title`, `slug`, `cuisine_id`, `description`, `image_url`, `is_veg`, `is_high_protein`, `calories`, `proteins_g`, `carbs_g`, `fats_g`, `prep_time`, `cook_time`, `servings`, `ingredients_json`, `steps_json`, `mood_tags_json`, `views_count`) VALUES
('Slow-Cooked Vegetable Stew', 'slow-cooked-vegetable-stew', 1, 'Gentle, warming stew that simmers slowly - perfect for a peaceful, relaxed evening.', 'https://www.thespruceeats.com/thmb/FN0DUFP1pCPQaaDg2Y9GMgeGIgo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/slow-cooker-vegetable-stew-2246305-hero-01-a1aae382702f48ea968a75f1d0a5386e.jpg', 1, 0, 280, 8.0, 45.0, 8.0, 15, 60, 4,
'[{"qty": "2", "unit": "cups", "item": "mixed vegetables (carrots, potatoes, beans)"}, {"qty": "1", "unit": "onion", "item": "diced"}, {"qty": "4", "unit": "cups", "item": "vegetable broth"}, {"qty": "2", "unit": "cloves", "item": "garlic, minced"}, {"qty": "1", "unit": "tsp", "item": "thyme"}, {"qty": "1", "unit": "tsp", "item": "rosemary"}, {"qty": "2", "unit": "tbsp", "item": "olive oil"}, {"qty": "1", "unit": "tbsp", "item": "tomato paste"}, {"qty": "1", "unit": "cup", "item": "barley or rice"}]',
'[{"step": 1, "instruction": "Sauté onions and garlic in olive oil until soft."}, {"step": 2, "instruction": "Add vegetables, tomato paste, and herbs. Stir for 2 minutes."}, {"step": 3, "instruction": "Add broth and barley. Bring to boil, then reduce heat."}, {"step": 4, "instruction": "Simmer covered for 50-60 minutes until vegetables are tender. Season and serve warm."}]',
'["relaxed"]', 67),

('Chamomile Lavender Tea', 'chamomile-lavender-tea', 7, 'Calming herbal tea blend that soothes the mind and brings tranquility.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMFeRXK_h0likB2nrxh5utHxOov6rAExtKGA&s', 1, 0, 5, 0.0, 1.0, 0.0, 5, 10, 1,
'[{"qty": "2", "unit": "tsp", "item": "chamomile flowers"}, {"qty": "1", "unit": "tsp", "item": "dried lavender"}, {"qty": "1", "unit": "cup", "item": "boiling water"}, {"qty": "1", "unit": "tsp", "item": "honey (optional)"}, {"qty": "1", "unit": "slice", "item": "lemon (optional)"}]',
'[{"step": 1, "instruction": "Combine chamomile and lavender in a tea infuser."}, {"step": 2, "instruction": "Pour boiling water over herbs. Steep for 8-10 minutes."}, {"step": 3, "instruction": "Strain, add honey and lemon if desired. Sip slowly and relax."}]',
'["relaxed"]', 89),

('Congee with Ginger', 'congee-with-ginger', 4, 'Warm, silky rice porridge that comforts and grounds you - a slow-food classic.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRixA7D5DUcF_oXCGWgN7DJ_saKD8Ojj63tHg&s', 1, 0, 180, 4.0, 35.0, 2.0, 10, 90, 2,
'[{"qty": "1/2", "unit": "cup", "item": "jasmine rice"}, {"qty": "6", "unit": "cups", "item": "water or vegetable broth"}, {"qty": "2", "unit": "inch", "item": "ginger, sliced"}, {"qty": "2", "unit": "cloves", "item": "garlic, minced"}, {"qty": "1", "unit": "tbsp", "item": "soy sauce"}, {"qty": "1", "unit": "tsp", "item": "sesame oil"}, {"qty": "2", "unit": "tbsp", "item": "scallions, chopped"}, {"qty": "1", "unit": "tbsp", "item": "cilantro"}, {"qty": "1", "unit": "egg", "item": "soft-boiled (optional)"}]',
'[{"step": 1, "instruction": "Rinse rice until water runs clear."}, {"step": 2, "instruction": "Combine rice, water, ginger, and garlic in pot. Bring to boil."}, {"step": 3, "instruction": "Reduce to low heat, simmer 60-90 minutes, stirring occasionally until creamy."}, {"step": 4, "instruction": "Season with soy sauce and sesame oil. Top with scallions, cilantro, and soft-boiled egg."}]',
'["relaxed"]', 54);

-- Rainy Mood Recipes
INSERT INTO `recipes` (`title`, `slug`, `cuisine_id`, `description`, `image_url`, `is_veg`, `is_high_protein`, `calories`, `proteins_g`, `carbs_g`, `fats_g`, `prep_time`, `cook_time`, `servings`, `ingredients_json`, `steps_json`, `mood_tags_json`, `views_count`) VALUES
('Spiced Pakoras', 'spiced-pakoras', 2, 'Crispy, golden-fried pakoras spiced perfectly - ideal for rainy day tea time!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlSoug9wQefKZ1e5ElkZtZLyqxPseoa-0n6A&s', 1, 0, 300, 6.0, 45.0, 12.0, 15, 15, 3,
'[{"qty": "1", "unit": "cup", "item": "gram flour (besan)"}, {"qty": "1", "unit": "cup", "item": "sliced onions"}, {"qty": "1/2", "unit": "cup", "item": "spinach, chopped"}, {"qty": "1", "unit": "tsp", "item": "red chili powder"}, {"qty": "1/2", "unit": "tsp", "item": "turmeric"}, {"qty": "1/2", "unit": "tsp", "item": "salt"}, {"qty": "1/2", "unit": "cup", "item": "water"}, {"qty": "for frying", "unit": "", "item": "oil"}]',
'[{"step": 1, "instruction": "Mix gram flour, spices, and water to make a thick batter."}, {"step": 2, "instruction": "Add onions and spinach to the batter and mix well."}, {"step": 3, "instruction": "Heat oil in a pan. Drop spoonfuls of batter and fry until golden."}, {"step": 4, "instruction": "Drain excess oil and serve hot with chutney."}]',
'["rainy"]', 34),

('Hot Ginger Tea', 'hot-ginger-tea', 7, 'Warm and aromatic ginger tea that comforts the soul on a rainy day.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5Uky90x3MWMxTEuVsQ_iNfwzdwWXS2Irkfw&s', 1, 0, 50, 0.5, 10.0, 0.0, 5, 10, 1,
'[{"qty": "2", "unit": "cups", "item": "water"}, {"qty": "1", "unit": "inch", "item": "fresh ginger, sliced"}, {"qty": "1", "unit": "tsp", "item": "black tea leaves"}, {"qty": "1", "unit": "tbsp", "item": "honey (optional)"}]',
'[{"step": 1, "instruction": "Boil water with ginger slices for 5 minutes."}, {"step": 2, "instruction": "Add tea leaves and simmer 2 minutes."}, {"step": 3, "instruction": "Strain, add honey if desired, and serve hot."}]',
'["rainy"]', 56),

('Steamy Pork Buns', 'steamy-pork-buns', 4, 'Warm, fluffy steamed buns filled with savory pork - perfect comfort food for a rainy day!', 'https://eatlittlebird.com/wp-content/uploads/2021/09/char-siu-bao-3.jpg', 0, 1, 320, 18.0, 38.0, 12.0, 30, 25, 4,
'[{"qty": "2", "unit": "cups", "item": "all-purpose flour"}, {"qty": "1", "unit": "tsp", "item": "yeast"}, {"qty": "1", "unit": "tsp", "item": "sugar"}, {"qty": "1/2", "unit": "cup", "item": "warm water"}, {"qty": "1/2", "unit": "lb", "item": "ground pork"}, {"qty": "2", "unit": "tbsp", "item": "hoisin sauce"}, {"qty": "1", "unit": "tbsp", "item": "soy sauce"}, {"qty": "2", "unit": "cloves", "item": "garlic, minced"}, {"qty": "1", "unit": "tbsp", "item": "ginger, minced"}, {"qty": "2", "unit": "tbsp", "item": "scallions, chopped"}]',
'[{"step": 1, "instruction": "Make dough: mix flour, yeast, sugar, and water. Knead, let rise 1 hour."}, {"step": 2, "instruction": "Cook pork with hoisin, soy sauce, garlic, and ginger until done."}, {"step": 3, "instruction": "Roll dough into circles, fill with pork mixture, pleat and seal."}, {"step": 4, "instruction": "Steam buns for 15-20 minutes until fluffy. Serve hot with soy sauce."}]',
'["rainy"]', 98),

('Hot and Sour Soup', 'hot-and-sour-soup', 4, 'Warming, tangy soup with mushrooms and tofu - the ultimate rainy day comfort!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKKz6H9yI4Nx9ervLBRHxfogGrnz5CUqm_4Q&s', 1, 0, 180, 8.0, 22.0, 6.0, 15, 20, 3,
'[{"qty": "6", "unit": "cups", "item": "vegetable broth"}, {"qty": "4", "unit": "oz", "item": "shiitake mushrooms, sliced"}, {"qty": "4", "unit": "oz", "item": "firm tofu, cubed"}, {"qty": "2", "unit": "tbsp", "item": "rice vinegar"}, {"qty": "1", "unit": "tbsp", "item": "soy sauce"}, {"qty": "1", "unit": "tsp", "item": "white pepper"}, {"qty": "1", "unit": "tsp", "item": "chili paste"}, {"qty": "2", "unit": "tbsp", "item": "cornstarch"}, {"qty": "1", "unit": "egg", "item": "beaten"}, {"qty": "2", "unit": "tbsp", "item": "scallions"}, {"qty": "1", "unit": "tsp", "item": "sesame oil"}]',
'[{"step": 1, "instruction": "Bring broth to boil. Add mushrooms and tofu, simmer 10 minutes."}, {"step": 2, "instruction": "Mix cornstarch with water, add to soup to thicken."}, {"step": 3, "instruction": "Add vinegar, soy sauce, white pepper, and chili paste."}, {"step": 4, "instruction": "Slowly drizzle in beaten egg while stirring. Garnish with scallions and sesame oil."}]',
'["rainy"]', 124),

('Masala Corn Chaat', 'masala-corn-chaat', 2, 'Warm, spicy masala corn tossed with butter and tangy spices – perfect during monsoon rains.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5Fh5n8eZy7yXz7m4FQmC7W9W0n1m0g&s', 1, 0, 220, 7.0, 32.0, 8.0, 10, 10, 2,
'[{"qty": "2", "unit": "cups", "item": "boiled sweet corn"}, {"qty": "1", "unit": "tbsp", "item": "butter"}, {"qty": "1/2", "unit": "tsp", "item": "red chili powder"}, {"qty": "1/2", "unit": "tsp", "item": "chaat masala"}, {"qty": "1", "unit": "tbsp", "item": "lemon juice"}, {"qty": "to taste", "unit": "", "item": "salt"}, {"qty": "2", "unit": "tbsp", "item": "chopped coriander"}]',
'[{"step": 1, "instruction": "Heat butter in a pan and add boiled corn."}, {"step": 2, "instruction": "Add chili powder, chaat masala, and salt."}, {"step": 3, "instruction": "Mix well and cook for 2–3 minutes."}, {"step": 4, "instruction": "Turn off heat, add lemon juice and coriander. Serve warm."}]',
'["rainy"]', 41),

('Chicken Noodle Soup', 'chicken-noodle-soup', 4, 'Light yet comforting chicken noodle soup that warms you up on cold rainy evenings.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnB9m8J1Hk9P3R3nZ9d8V9w&s', 0, 1, 260, 20.0, 24.0, 7.0, 15, 25, 3,
'[{"qty": "6", "unit": "cups", "item": "chicken broth"}, {"qty": "200", "unit": "g", "item": "chicken breast, shredded"}, {"qty": "1", "unit": "cup", "item": "egg noodles"}, {"qty": "1", "unit": "cup", "item": "mixed vegetables"}, {"qty": "1", "unit": "tsp", "item": "garlic, minced"}, {"qty": "to taste", "unit": "", "item": "salt and pepper"}]',
'[{"step": 1, "instruction": "Bring chicken broth to a boil."}, {"step": 2, "instruction": "Add garlic, vegetables, and noodles. Cook until noodles soften."}, {"step": 3, "instruction": "Add shredded chicken, salt, and pepper."}, {"step": 4, "instruction": "Simmer for 5 minutes and serve hot."}]',
'["rainy"]', 67),

('Aloo Pakora', 'aloo-pakora', 2, 'Crispy potato fritters coated in spiced gram flour – a classic rainy day snack.', 'https://silkroadrecipes.com/wp-content/uploads/2022/06/Potato-Pakora-square.jpg', 1, 0, 280, 5.0, 40.0, 11.0, 10, 15, 3,
'[{"qty": "2", "unit": "medium", "item": "potatoes, sliced"}, {"qty": "1", "unit": "cup", "item": "gram flour (besan)"}, {"qty": "1/2", "unit": "tsp", "item": "turmeric"}, {"qty": "1", "unit": "tsp", "item": "red chili powder"}, {"qty": "to taste", "unit": "", "item": "salt"}, {"qty": "as needed", "unit": "", "item": "water"}, {"qty": "for frying", "unit": "", "item": "oil"}]',
'[{"step": 1, "instruction": "Mix gram flour, spices, salt, and water to make batter."}, {"step": 2, "instruction": "Dip potato slices into batter."}, {"step": 3, "instruction": "Deep fry until golden and crisp."}, {"step": 4, "instruction": "Drain excess oil and serve hot."}]',
'["rainy"]', 89),

('Tomato Basil Soup', 'tomato-basil-soup', 5, 'Smooth and warming tomato basil soup, comforting and light for rainy weather.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZBv7Yy4M&s', 1, 0, 150, 4.0, 20.0, 5.0, 10, 20, 2,
'[{"qty": "4", "unit": "cups", "item": "tomatoes, chopped"}, {"qty": "2", "unit": "cups", "item": "vegetable stock"}, {"qty": "1", "unit": "tbsp", "item": "olive oil"}, {"qty": "2", "unit": "cloves", "item": "garlic"}, {"qty": "1", "unit": "tbsp", "item": "fresh basil"}, {"qty": "to taste", "unit": "", "item": "salt and pepper"}]',
'[{"step": 1, "instruction": "Heat olive oil and sauté garlic."}, {"step": 2, "instruction": "Add tomatoes and cook until soft."}, {"step": 3, "instruction": "Add stock and simmer for 10 minutes."}, {"step": 4, "instruction": "Blend smooth, add basil, season, and serve warm."}]',
'["rainy"]', 53),

('Hot Chocolate', 'hot-chocolate', 6, 'Rich and creamy hot chocolate to enjoy while listening to rain outside.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJR56cx20S0ZqTvNfkK990huQWxCgRxHbuaw&s', 1, 0, 210, 6.0, 26.0, 9.0, 5, 10, 1,
'[{"qty": "1", "unit": "cup", "item": "milk"}, {"qty": "1", "unit": "tbsp", "item": "cocoa powder"}, {"qty": "1", "unit": "tbsp", "item": "sugar"}, {"qty": "1/4", "unit": "tsp", "item": "vanilla essence"}]',
'[{"step": 1, "instruction": "Heat milk in a saucepan."}, {"step": 2, "instruction": "Add cocoa powder and sugar, whisk well."}, {"step": 3, "instruction": "Simmer for 2–3 minutes."}, {"step": 4, "instruction": "Add vanilla essence and serve hot."}]',
'["rainy"]', 112);



-- Sunny Mood Recipes
INSERT INTO `recipes` (`title`, `slug`, `cuisine_id`, `description`, `image_url`, `is_veg`, `is_high_protein`, `calories`, `proteins_g`, `carbs_g`, `fats_g`, `prep_time`, `cook_time`, `servings`, `ingredients_json`, `steps_json`, `mood_tags_json`, `views_count`) VALUES
('Citrus Quinoa Salad', 'citrus-quinoa-salad', 3, 'Bright, fresh salad with citrus fruits and quinoa - tastes like sunshine in a bowl!', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800', 1, 1, 320, 12.0, 48.0, 10.0, 15, 0, 2,
'[{"qty": "1", "unit": "cup", "item": "quinoa, cooked and cooled"}, {"qty": "1", "unit": "orange", "item": "segmented"}, {"qty": "1", "unit": "grapefruit", "item": "segmented"}, {"qty": "1/4", "unit": "cup", "item": "red onion, thinly sliced"}, {"qty": "1/4", "unit": "cup", "item": "fresh mint"}, {"qty": "1/4", "unit": "cup", "item": "feta cheese, crumbled"}, {"qty": "2", "unit": "tbsp", "item": "olive oil"}, {"qty": "1", "unit": "tbsp", "item": "lemon juice"}, {"qty": "1", "unit": "tsp", "item": "honey"}, {"qty": "1/4", "unit": "cup", "item": "pistachios, chopped"}]',
'[{"step": 1, "instruction": "Combine quinoa with orange and grapefruit segments."}, {"step": 2, "instruction": "Add red onion, mint, and feta cheese."}, {"step": 3, "instruction": "Whisk olive oil, lemon juice, and honey for dressing."}, {"step": 4, "instruction": "Toss salad with dressing, top with pistachios. Serve chilled."}]',
'["sunny"]', 89),

('Iced Matcha Latte', 'iced-matcha-latte', 7, 'Cool, refreshing matcha latte - perfect for a bright, sunny day!', 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=800', 1, 0, 85, 2.0, 12.0, 3.0, 5, 0, 1,
'[{"qty": "1", "unit": "tsp", "item": "matcha powder"}, {"qty": "2", "unit": "tbsp", "item": "hot water"}, {"qty": "1", "unit": "cup", "item": "almond milk or milk"}, {"qty": "1", "unit": "tbsp", "item": "honey or maple syrup"}, {"qty": "1/2", "unit": "cup", "item": "ice cubes"}, {"qty": "1", "unit": "pinch", "item": "vanilla extract (optional)"}]',
'[{"step": 1, "instruction": "Whisk matcha powder with hot water until frothy and smooth."}, {"step": 2, "instruction": "Add honey and vanilla, mix well."}, {"step": 3, "instruction": "Fill glass with ice, pour in milk, then top with matcha mixture."}, {"step": 4, "instruction": "Stir gently and enjoy immediately!"}]',
'["sunny"]', 156),

('Chilled Soba Noodles', 'chilled-soba-noodles', 5, 'Light, refreshing cold noodles with dipping sauce - ideal for hot, sunny days!', 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800', 1, 0, 280, 10.0, 52.0, 4.0, 10, 8, 2,
'[{"qty": "8", "unit": "oz", "item": "soba noodles"}, {"qty": "1/4", "unit": "cup", "item": "soy sauce"}, {"qty": "1/4", "unit": "cup", "item": "mirin"}, {"qty": "1", "unit": "tbsp", "item": "rice vinegar"}, {"qty": "1", "unit": "tsp", "item": "sugar"}, {"qty": "1", "unit": "cup", "item": "dashi stock"}, {"qty": "2", "unit": "tbsp", "item": "scallions, chopped"}, {"qty": "1", "unit": "tbsp", "item": "sesame seeds"}, {"qty": "1", "unit": "sheet", "item": "nori, shredded"}, {"qty": "1", "unit": "tsp", "item": "wasabi"}]',
'[{"step": 1, "instruction": "Cook soba noodles according to package. Rinse in cold water until cool."}, {"step": 2, "instruction": "Mix soy sauce, mirin, vinegar, sugar, and dashi for dipping sauce."}, {"step": 3, "instruction": "Arrange noodles on plate, garnish with scallions, sesame seeds, and nori."}, {"step": 4, "instruction": "Serve with dipping sauce and wasabi on the side."}]',
'["sunny"]', 112),

('Tropical Fruit Smoothie Bowl', 'tropical-fruit-smoothie-bowl', 3, 'Vibrant, colorful smoothie bowl topped with fresh tropical fruits - sunshine in every bite!', 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800', 1, 0, 280, 6.0, 58.0, 8.0, 10, 0, 1,
'[{"qty": "1", "unit": "cup", "item": "frozen mango"}, {"qty": "1/2", "unit": "cup", "item": "frozen pineapple"}, {"qty": "1", "unit": "banana", "item": "frozen"}, {"qty": "1/2", "unit": "cup", "item": "coconut milk"}, {"qty": "1/4", "unit": "cup", "item": "fresh mango, diced"}, {"qty": "1/4", "unit": "cup", "item": "fresh pineapple, diced"}, {"qty": "2", "unit": "tbsp", "item": "coconut flakes"}, {"qty": "1", "unit": "tbsp", "item": "chia seeds"}, {"qty": "1", "unit": "tbsp", "item": "honey"}]',
'[{"step": 1, "instruction": "Blend frozen fruits with coconut milk until thick and smooth."}, {"step": 2, "instruction": "Pour into bowl, creating a smooth surface."}, {"step": 3, "instruction": "Artistically arrange fresh mango, pineapple, coconut flakes, and chia seeds on top."}, {"step": 4, "instruction": "Drizzle with honey and serve immediately!"}]',
'["sunny"]', 98),

('Iced Tropical Smoothie', 'iced-tropical-smoothie', 3, 'Cool, fruity smoothie with pineapple, mango, and coconut - perfect sunny day refreshment!', 'https://www.jessicagavin.com/wp-content/uploads/2020/06/tropical-smoothie-5-1200.jpg', 1, 1, 180, 5.0, 40.0, 2.0, 5, 0, 2,
'[{"qty": "1", "unit": "cup", "item": "mango, frozen"}, {"qty": "1", "unit": "cup", "item": "pineapple, frozen"}, {"qty": "1/2", "unit": "cup", "item": "coconut milk"}, {"qty": "1", "unit": "cup", "item": "ice cubes"}, {"qty": "1", "unit": "tsp", "item": "honey"}]',
'[{"step": 1, "instruction": "Blend all ingredients until smooth."}, {"step": 2, "instruction": "Pour into glasses and garnish with pineapple slices or mint leaves."}]',
'["sunny"]', 61);

-- Insert a test user (password: test123 - hash will be generated by PHP)
-- Password hash for 'test123' using bcrypt: $2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi
INSERT INTO `users` (`username`, `email`, `password_hash`, `is_premium`) VALUES
('testuser', 'test@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 0);


